### ISSUE TITLE
Add extra columns to synthetic data

### ISSUE THREAD

**Issue by 3ntr0phy** [sdv-dev/SDV#1032]
Hi everyone, 
I have a really simple and naive question.
I was wondering if it would be possible to augment the initial dataset not only by creating extra rows but also by creating new columns, similar to the ones learnt.
Thanks.

**Comment by npatki** [comment]
Hi @3ntr0phy, nice to meet you!

Creating extra columns is not currently possible in the SDV. One complexity is that the columns can describe completely different properties. For example if you have a table for your product users, columns might be: `name`, `age`, `date_joined`, `browser_used`, `purchase_amount` etc. We would somehow have to determine which new properties to add and then also determine what the values should be.

Maybe there is a way forward for other types of data. Can you describe your use case and data table a bit more? What kind of information would you expect the synthetic data models to learn? What kinds of new columns would you expect?

**Comment by npatki** [comment]
Hi @3ntr0phy, I'll mark the question as closed since we've answered your original Q*. If you'd like us to support this feature, you are welcome to [file a new feature request](https://github.com/sdv-dev/SDV/issues/new/choose) that we can use to discuss further & track progress. I think we'll need to get clearer on the expected usage, maybe with some examples.

*One other possibility that you can use today: Depending on the nature of your data, it may be possible to _transpose_ the data so that the columns become rows and the rows become columns. Then, you could use the SDV to add more rows (which were originally columns).

Feel free to reply to the issue if there's more to discuss and I will re-open it. Thanks!
