### ISSUE TITLE
How to use inequality constraints with datetime?

### ISSUE THREAD

**Issue by montasIET** [sdv-dev/SDV#1115]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.17.1
* Python version: 3.8.15
* Operating System: Windows 11 Pro

### Problem description

I'm using an inequality constraint with two columns of type 'datetime64[ns]' and I want that date1 is before date2, but I get the error:

`Traceback (most recent call last):
  File "minisogei_generation.py", line 41, in <module>
    model = GaussianCopula(constraints = c, table_metadata=metadata.get_table_meta('minisogei'),
  File "C:\Users\luimon\miniconda3\envs\minisogei\lib\site-packages\sdv\tabular\copulas.py", line 171, in __init__
    super().__init__(
  File "C:\Users\luimon\miniconda3\envs\minisogei\lib\site-packages\sdv\tabular\base.py", line 110, in __init__
    'If table_metadata is given {} must be None'.format(arg.__name__))
AttributeError: 'list' object has no attribute '__name__'`

How can I fix? Thanks

**Comment by npatki** [comment]
Hi @montasIET, it will be helpful if you could provide more information to us to help us replicate the issue.

1. Could you provide a snippet of the code where you are creating the constraint and creating the model? 
2. (If you have written it) Could you provide your `metadata.json` file?

**Comment by npatki** [comment]
Hi @montasIET, thanks for your reply and details! I might know what the issue is.

Right now, you cannot provide both metadata and constraints in the model. (We’re working on adding better documentation & usage for this feature.)

For now, you can directly add the constraint inside the metadata and then you only need to supply the metadata. Below is an example of how to do this,

```json
{  
  "fields": {
    ...
  },
  "constraints": [{
    "constraint": "sdv.constraints.tabular.Inequality",
    "low_column_name": "DATA_INIZIO_ATTIVITA",
    "high_column_name": "DATA_FINE_ATTIVITA"
  }]
}
```

**Comment by montasIET** [comment]
Hi @npatki, thanks for answering!
So, doing in this way it's not possible to define a custom constraint, is it?

**Comment by npatki** [comment]
Hi @montasIET, we call the `Inequality` constraint a **predefined constraint** because we have already defined its logic. Until we fix #1121, I don't think it will be possible to use it in your case.

However you can at any point create your own **custom constraint**. That is: You can write code to implement your own logic for what is allowed and how to achieve it in the synthetic data. [This User Guide](https://sdv.dev/SDV/user_guides/single_table/custom_constraints.html) should help you get started.

**Comment by montasIET** [comment]
@npatki sorry for reopening the thread, but I followed each step and got into this error:
raise MultipleConstraintsErrors('\n' + '\n\n'.join(map(str, errors)))
sdv.constraints.errors.MultipleConstraintsErrors:
Data is not valid for the 'CustomConstraint' constraint:
            FIELD_ONE     FIELD_TWO
0          ....                                            ....
1          ....                                            ....
2          ....                                            ....
3          ....                                            ....
4          ....                                            ....
+9995 more

(sorry I cannot share full data but it shows me values instead of **....**)

**Comment by npatki** [comment]
@montasIET can you start a new issue for this? It would be good to keep the current issue focused on the initial topic (using `Inequality` constraint)
