### ISSUE TITLE
S&P 500 data with PAR - synthetic data not usable 

### ISSUE THREAD

**Issue by antonma** [sdv-dev/SDV#1184]
### Environment details
* SDV version:  0.17.2
* Python version: 3.9.10
* Operating System: Windows / VS Code

### Problem description

I need to create synthetic data for S&P 500 on 15 minute timeframe. I followed this tutorial:
https://github.com/sdv-dev/SDV/blob/master/tutorials/timeseries_data/01_PAR_Model.ipynb

The problem is that the difference between the close (also for open, high and low) and the previous close is too big to be realistic. This volatility is unrealistic since we are on a 15 min time frame. 
The second issue is that the volume can get negative in the synthetic data which is not the case with the real data.

![image](https://user-images.githubusercontent.com/13572239/214285516-9dc3380d-30ee-4365-81a0-e26f73114d5a.png)

Any Ideas what I can do to make the synthetic data more realistic?

### What I already tried

This is my code.
```
from sdv import SDV
from sdv.timeseries import PAR
import pandas as pd

#%%
spx_df =  pd.read_csv("./input/SPX500_USD_15_2022_12.csv")
spx_df['Date'] = pd.to_datetime(spx_df['Date'])
spx_df.head()

#%%
sequence_index = 'Date'
model = PAR(sequence_index=sequence_index)
model.fit(spx_df)


# %%
model.sample()
# %%
model.save("SPX500_USD_15_2022_12.pkl")
# %%
df_synth = model.sample()
# %%
df_synth.head(20)
```

**Comment by npatki** [comment]
Hi @antonma nice to meet you,

Since you mention the synthetic data is _unusable_, I'm curious if you have a particular usage in mind? I ask because for some usages -- such as protecting privacy -- it may actually be beneficial to have more variation in the data.

### Your Code
It seems like you are missing `entity_columns`. I'm curious if your data represents only a single sequence (ie. a single stock) or whether it represents multiple sequences (ie. different stocks)?

**The PAR model is suited for multi-sequence data**, where a sequence is defined by the `entity_columns`. It is designed to create new synthetic sequences that don't necessarily correspond to the original. For example, if your real data corresponds to stock sequences such as `AAPL`, `AMZN`, `GOOG`, etc. then the synthetic data will have sequences for brand new companies such as `AAAA`, `BBBB`, `CCCC`.

If you are only looking to recreate a single sequence, then PAR may not be the best choice for you.

### Demo Dataset
When I run the `PAR model` on the multi-sequence [demo dataset in the tutorial](https://github.com/sdv-dev/SDV/blob/master/tutorials/timeseries_data/01_PAR_Model.ipynb), I find that that the daily differences are generally the same. Eg:

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/3227804/215907301-e4d5eca5-2118-4643-8884-2c995f421da7.png">

### Existing Issues
Currently, the PAR model cannot be set up to explicitly follow the `min` and `max` bounds that were observed in the real dataset. This feature request in being tracked in #745 and is currently in development to be resolved in a future release.

**Comment by npatki** [comment]
Hi @antonma, are you still exploring the PAR with the S&P 500 data?

I'm closing the issue since we answered your question a few weeks ago. We also found an existing, related issue -- and you're welcome to continue the conversation there too.

If you still have any thoughts or feedback, feel free to reply here and we can reopen this original issue.
