### ISSUE TITLE
Anomaly detection using TVAE, or CTGAN

### ISSUE THREAD

**Issue by adibmoh12** [sdv-dev/SDV#1230]
### Problem Description
I am new to this field forgive my naivity
I would like to use those model for anomaly detection, for a specific column, i tried something like that but it didn't work,

import pickle
with open('my_model.pkl', 'rb') as file:
    model = pickle.load(file)
encoded = model.encode(new_data)
reconstructed = model.decode(encoded)
error = mean_squared_error(new_data, reconstructed)

### Expected behavior

thanks
### Additional context

<Please provide any additional context that may be relevant to the issue here. If none, please remove this section.>

**Comment by npatki** [comment]
Hi @adibmoh12, the SDV is designed to create all-new synthetic data from the model. 

These models don't have any `encode` and `decode` functions (eg. see [CTGAN API](https://sdv.dev/SDV/api_reference/tabular/ctgan.html)).

If you haven't already, the [CTGAN User Guide](https://sdv.dev/SDV/user_guides/single_table/ctgan.html) and [TVAE User Guide](https://sdv.dev/SDV/user_guides/single_table/tvae.html) would be good places to get familiar with the features. That may help you determine if these can use used for your use case.

**Comment by adibmoh12** [comment]
thanks, but what about TVAE, isnt it encode and decode?

**Comment by npatki** [comment]
Hi @adibmoh12, same with TVAE. Feel free to go through the [TVAE User Guide](https://sdv.dev/SDV/user_guides/single_table/tvae.html) and [TVAE Sampling API](https://sdv.dev/SDV/api_reference/tabular/api/sdv.tabular.ctgan.TVAE.sample.html).

Similar to CTGAN, you are free to use the model to sample all new synthetic data. All you need to provide is the number of rows.

**Comment by npatki** [comment]
Hi @adibmoh12, I hope you were able to explore the CTGAN and TVAE models.

Note that our models are specifically designed to create synthetic data (as opposed to anomaly detection). However, it may be possible to use the synthetic data to help detect anomalies in the real data -- but this would be a separate task, and an area out-of-scope for the SDV library.

I'm going to close this issue since it's been a few weeks. But if you have any other thoughts or feedback, please feel free to reply and we can reopen the issue.
