### ISSUE TITLE
CopulaGAN fit model doesn't use gpu...

### ISSUE THREAD

**Issue by caprone** [sdv-dev/SDV#1271]
HI
I'm training CopulaGAN model, but it' is very slow because doesn't run on GPU...how it's possible?

**Comment by pvk-developer** [comment]
Hi @caprone ,

Sometimes `CopulaGAN` may take longer times to fit depending on the data, size and epochs used.

However, it is also very important to keep in mind that it depends on your operating system and whether or not you have installed properly the drivers for your `GPU`  and if you have `cuda` enabled. In order to ensure that you can train using the `GPU` you can run the following code in a python interpreter in the same environment that you have for `SDV`:

```python
import torch
print(torch.cuda.is_available())
```
If the output is `True` that means that `GPU` should be usable by `CTGAN`. The following step to ensure that `CTGAN` will use the `GPU` is to provide `CTGAN` model with the parameter `cuda=True` (which by default its already set). However, if the output is `False` then it means that `torch` is not able to find or use `cuda` / `GPU` for fitting which means that you should re-install the drivers and `cuda` for your `GPU`.

Finally, once your environment is ready to use `GPU` before starting the fit process you can try monitoring your `GPU` activity and ensure that it starts increasing after running `model.fit(data)`.

**Comment by caprone** [comment]
HI and thanks for answered; :)
I use pytorch models, and tf/keras models daily..and obviously all turn up my RTX...:)) (all this frameworks are updated to last releases...)
I  tried CopulaGAN, and as I can see from source code, also it works with "transformers" ...If I have time, I'll take a look at the code...but right now as now this models not run on GPU...

**Comment by pvk-developer** [comment]
On my end I managed to get `CTGAN` fit on a `gpu` / `cuda` device as seen in the images below (on the left side you can see the `nvidia-smi` which after running fit gets a new process being run on it by `python` which is the fitting of `CTGAN`) :
* [Before running `CTGAN.fit`](https://user-images.githubusercontent.com/41479552/220934251-be6dfb8d-7068-4018-a47c-e726b4a4bcf4.png)
* [While running `CTGAN.fit`](https://user-images.githubusercontent.com/41479552/220934247-2bea8967-daef-46be-b115-13627e4b473a.png)

I understand that the performance maybe is not as expected, but I also believe that doesn't mean that `CTGAN` does not run on `GPU`.

Feel free to take a look and suggest any improvements to our [CTGAN](https://github.com/sdv-dev/CTGAN/blob/master/ctgan/synthesizers/ctgan.py) model.

**Comment by pvk-developer** [comment]
Hi @caprone, I’m closing this off since we’ve worked through the issue. If you are still running into issues, feel free to reply and we can reopen for investigation
