### ISSUE TITLE
Support for multiple uuid4 types in a table

### ISSUE THREAD

**Issue by HotDiggityDogz** [sdv-dev/SDV#1303]
### Problem Description

If a table has more than one column with datatype of uuid4,  then when generating synthetic data both columns get the same uuid4 value in any given row.  In the original data, the uuids are different (and refer to different entities) .
![Screenshot 2023-03-09 at 11 47 15 AM](https://user-images.githubusercontent.com/4432015/224146286-f5fcf093-7933-4579-8ad4-fa1d153cb20e.png)

### Expected behavior

Each column of type 'uuid4' should have it's own value generated within a a row.  

### Additional context

Changing models or distribution within a model did not fix this.
The values are also exactly the same every time data is generated (unlike data of other types)

**Comment by npatki** [comment]
Hi @HotDiggityDogz (great username!), thanks for testing out the SDV 1.0 Beta and providing feedback.

I can replicate the issue. I agree it's strange that both columns always have the same (randomly generated) values. In real world settings, I imagine you would expect the values to be different. 

### Context
Starting from SDV 1.0, we control the randomization so that it's possible to deterministically sample the same data whenever you create a synthesizer. The [Controlling Randomization section](https://docs.sdv.dev/sdv/single-table-data/sampling#controlling-randomization) has more details about this.

It seems like we are fixing the same seed for each faker, which is resulting in the same random values for both columns.

> The values are also exactly the same every time data is generated (unlike data of other types)

I'm note quite sure what you mean by this? I see that every time I call `sample`, there are new values being generated.
 
![image](https://user-images.githubusercontent.com/3227804/224173173-9259baea-37cd-477b-838f-5c71faceb054.png)

**Comment by npatki** [comment]
FYI This issue will be resolved in our [RDT library](https://docs.sdv.dev/rdt), which is responsible for the data preprocessing and anonymization. 

I've filed [RDT issue 619](https://github.com/sdv-dev/RDT/issues/619) with more details, and we'll use it to track the fix. In the meantime, we can keep this issue open until the fix is propagated back into the SDV library.

**Comment by npatki** [comment]
Hi @HotDiggityDogz, this issue has now been fixed and is part of the latest release (SDV 1.0.1).
