### ISSUE TITLE
Documentation suggests "path" keyword argument in save method

### ISSUE THREAD

**Issue by arvkevi** [sdv-dev/SDV#1344]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.0.0 
* Python version: 3.9.13
* Operating System: macOS

### Error Description

[The documentation](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer#save) suggests there is a `path` keyword argument in the `save` method, but the [`save` method of the `BaseSynthesizer` class](https://github.com/sdv-dev/SDV/blob/1f216d7de6f55855b78942de147286f3122a03c9/sdv/single_table/base.py#L459) does not have a keyword argument.

### Steps to reproduce

```python
import numpy as np
import pandas as pd

from sdv.metadata import SingleTableMetadata
from sdv.single_table import CTGANSynthesizer

a = pd.DataFrame(np.random.randint(0, 1, (100, 10)), columns=list("abcdefghij"))

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data=a)


synthesizer = CTGANSynthesizer(
    metadata,
)
synthesizer.fit(a)
synthesizer.save(path="my_synthesizer.pkl")
```

This raised a `TypeError`:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/var/folders/g2/b2m1qtks3_j97bl9ttnkrssw0000gp/T/ipykernel_89741/1919952502.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/g2/b2m1qtks3_j97bl9ttnkrssw0000gp/T/ipykernel_89741/1919952502.py) in ()
     15 )
     16 synthesizer.fit(a)
---> 17 synthesizer.save(path="my_synthesizer.pkl")

TypeError: save() got an unexpected keyword argument 'path'
```

Passing a string as an argument works as expected:

```python
synthesizer.save("my_synthesizer.pkl")
```

I'm happy to open a PR, provided some guidance, and if you think it would be helpful. Congrats on the v1.0 release btw, I love this library!

**Comment by npatki** [comment]
Hi @arvkevi thanks for catching this and providing the details.

This is a mistake in the docs. The correct parameter name should be `filepath` instead of `path`, so the following should work.

```python
synthesizer.save(filepath='my_synthesizer.pkl')
```

And calling it by the keyword name is indeed optional. So as you mention, you can always call `save` without it. 

I've updated the docs now (may require a refresh to see). Seems like all our synthesizers accidentally had `path` instead of `filepath`.
<img width="947" alt="image" src="https://user-images.githubusercontent.com/3227804/228668962-41df61ea-3c2a-4f18-8889-a3d47385a2c0.png">

**Comment by arvkevi** [comment]
Thanks, @npatki. Your suggestion worked on my end and the `save` docs for all synthesizers read "filepath" now.

**Comment by npatki** [comment]
Great thanks for confirming 😃 Closing off the issue!
