### ISSUE TITLE
Conditional Sampling for CTGAN and CopulaGAN is slow

### ISSUE THREAD

**Issue by Shruti-codes** [sdv-dev/SDV#1419]
I'm trying to generate a PII column for a dataframe using sample_remaining_columns.
Note that the trained synthesizer also has a CustomConstraint and the PII column has been transformed using AnonymizedFaker class.

`synthetic_data = synthesizer.sample_remaining_columns(df_new)`

**Error**
ValueError: Unable to sample any rows for the given conditions. Try increasing `max_tries_per_batch` (currently: 100). Note that increasing this value will also increase the sampling time.

I have tried multiple dimensions for df_new.

**EDIT**
I could generate some rows by playing around with max_tries_per_batch and batch_size.
Is there some good practice to ensure optimal values of above parameters?

**Comment by npatki** [comment]
Hi @Shruti-codes, nice to meet you. 

Since you were able to get the conditional sampling to work (after updating `max_tries_per_batch` and `batch_size`), I'll update the title to reflect this. 

The CTGAN and CopulaGAN are not very efficient when it comes to most conditions. They use a **reject sampling** approach which means they:
1.  Sample some data freely (using `batch_size`)
2. Delete any rows that don't match the required conditions
3. Repeat the process until all the data is created (up to `max_tries_per_batch`)

If you are having problems, it indicates that the conditions you are asking for may be very rare -- therefore many tries are required. Some suggestions:

- Use a large `batch_size` and `max_tries_per_batch`. Unfortunately, there is no one-size-fits-all solution to optimize this, as it depends on how rare the conditions are compared to the data that you have fit.
- Try using a different synthesizer that is more efficient at conditional sampling, such as the [GaussianCopula Synthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer)

**Comment by Shruti-codes** [comment]
Sure. Thanks. 
Will try out both approaches.

**Comment by javialias** [comment]
Hi. With respect to Conditional Sampling, when you say that CTGAN and CopulaGAN use reject sampling, I'm understanding that GaussianCopula does not. From what I read in the SDV paper, the copula model is capable of calculating the conditional distribution and then sample from it, is that right? In that case, the "max_tries_per_batch" is useless?

I'm asking this because I've been trying to use the GaussianCopula model for missing value imputation (creating a Condition object for every row that has missing values) but the synthesizer fails to fill those values, with the same error "ValueError: Unable to sample any rows for the given conditions."

Could you give some information about this? Do you think that it could be possible to use this tool for imputation?

**Comment by npatki** [comment]
Hi @javialias as this overall issue was for CTGAN/CopulaGAN, do you mind filing a new one for your question? You can also use the space to provide more detail about your synthesizer. For example, what settings did you use? Do you add constraints? etc.
