### ISSUE TITLE
Missing modules for latest version 1.1.0

### ISSUE THREAD

**Issue by MajidAdams** [sdv-dev/SDV#1422]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: v1.1.0
* Python version: v3.9.16
* Operating System: windows 11

### Error Description

First time installation of sdv, and I installed the version v1.1.0. I was trying to generate tabular data with it but it keeps giving the error "ModuleNotFoundError: No module named 'sdv.tabular'". I also checked the directory and found out it was incomplete, only found the special methods/attributes. See screenshot below.

### Steps to reproduce

pip install sdv on an environment that has never had sdv installed on it. Then import CTGAN from sdv.tabular

```
!pip install sdv
from sdv.tabular import CTGAN
```
![Screenshot (80)](https://github.com/sdv-dev/SDV/assets/27727529/cf2145de-bb21-43ff-b1d7-d79a2b3e5c77)

**Comment by npatki** [comment]
Hi @MajidAdams are you still running into this problem? 

A `ModuleNotFound` error typically indicates an issue with installation or usage. In this case, the code you are using

```python
from sdv.tabular import CTGAN
```

Is old code for older versions of the SDV.  Please see the recent [SDV documentation](https://docs.sdv.dev/sdv) for recent code.

PS. In the new website, we have also added a [Troubleshooting section](https://docs.sdv.dev/sdv/installation#troubleshooting) that you can browse through.

I'll close this issue since it's been a few weeks . If you are still having problems, feel free to reply and I can reopen the issue.
