### ISSUE TITLE
SynthesizerInputError: Invalid transformer 'NoneType' for a primary or alternate key 'ID'. Please use 'AnonymizedFaker' or 'RegexGenerator' instead.

### ISSUE THREAD

**Issue by kiransview** [sdv-dev/SDV#1448]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.1.0
* Python version: 3.9.12
* Operating System: Windows 11

### Problem description

I am working on a multi-table dataset for synthetic data generation. So i have assigned all the keys as mentioned in the demo and added and updated the keys but when I run the HMA model, during fit i am getting the above-mentioned error.

**Comment by npatki** [comment]
Hi @kiransview, nice to meet you. We need more detail in order to understand and replicate your issue. Could you provide the following info?

1. Link to the demo that you are referencing
2. Your code for creating a synthesizer, updating it, fitting it and sampling.
3. Provide the full stack trace that is printed out
4. (If possible) Your metadata JSON file will also be useful, as some bugs may be dependent on the column types and schemas

**Comment by npatki** [comment]
Hi @kiransview, are you still encountering this problem?

This issue hasn't been active for a few weeks so I'm closing it off as unable to replicate. If you are able to answer any of the above Qs, feel free to reply anyways. We can always re-open the issue to continue the investigation.
