### ISSUE TITLE
How can I annotate integer columns rather than numerical

### ISSUE THREAD

**Issue by thaddywu** [sdv-dev/SDV#1460]
Please see the title. In the newest official document, SDV supports `numerical` annotation on columns. Is there fine-grained annotation for integers?
Thank you!

**Comment by JacopoMor** [comment]
@thaddywu  You have multiple options
![image](https://github.com/sdv-dev/SDV/assets/60231184/ffb5cab5-4627-4236-a1b8-aeb99bd47a65)

You can find more about it in the documentation
https://docs.sdv.dev/sdv/reference/metadata-spec/single-table-metadata-json

**Comment by npatki** [comment]
Hi @thaddywu, do you have anything else you'd like to discuss related to numerical columns? I'm closing off the issue since it's been inactive for a few weeks -- but feel free to reply and I can always reopen it.

(I'm still curious if there's something specific you want to achieve by designating something as `integer` as opposed to a float. Is there some place the SDV can do better?)
