### ISSUE TITLE
Resolve `DeprecationWarning` (np.find_common_type is deprecated.)

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#1469]
### Environment Details

* SDV version: 1.2.0 (latest)
* Numpy version: 1.25.0
* Python version: 3.10
* Operating System: Colab Notebook

### Error Description
When sampling from an HMA synthesizer, the following deprecation warning prints out multiple times:

```
/usr/local/lib/python3.10/dist-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
```

### Steps to reproduce
Paste the code below to trigger the warnings.

```python
import pandas as pd
import numpy as np
from sdv.metadata import MultiTableMetadata
from sdv.multi_table import HMASynthesizer

parent = pd.DataFrame(data={
    'id': ['id_' + str(i) for i in range(10)],
    'A': list(np.random.uniform(low=0, high=10, size=10)),
    'B': list(np.random.choice(['value_0', 'value_1', 'value_2'], size=10))
})

child = pd.DataFrame(data={
    'id': ['id_' + str(i) for i in range(100)],
    'parent_id': ['id_' + str(i) for i in list(np.random.randint(low=0, high=10, size=100))],
    'C': list(np.random.uniform(low=0, high=10, size=100))
})

metadata = MultiTableMetadata.load_from_dict({
    'tables': {
        'parent': {
            'primary_key': 'id',
            'columns': {
                'id': { 'sdtype': 'id', 'regex_format': 'id_\d{2}' },
                'A': { 'sdtype': 'numerical' },
                'B': { 'sdtype': 'categorical' }
            }
        },
        'child': {
            'primary_key': 'id',
            'columns': {
                'id': { 'sdtype': 'id', 'regex_format': '\d{3}' },
                'parent_id': { 'sdtype': 'id', 'regex_format': 'id_\d{2}' },
                'C': { 'sdtype': 'numerical' }
            }
        }
    },
    'relationships': [{
        'parent_table_name': 'parent',
        'parent_primary_key': 'id',
        'child_table_name': 'child',
        'child_foreign_key': 'parent_id'
    }]
})

synth = HMASynthesizer(metadata)
synth.fit({
    'parent': parent,
    'child': child
})
synth.sample(scale=1)
```

**Comment by JoshuaGhost** [comment]
Same problem here. The deprecation warning even halt the pytest when doing the test. But it seems that the reason of this warning is the call of `common = np.find_common_type([values.dtype, comps_array.dtype], [])` in pandas instead of in sdv at, e.g. following places:

- pandas/core/algorithms.py#522
- pandas/core/dtypes/cast.py#1641

(pandas version == 1.5.3)

One can simply resolve this warning by:
1. either updating the pandas to a more mordern version (2.0.3, for example) (issue: https://github.com/pandas-dev/pandas/pull/49569#issuecomment-1308300065)
2. or replacing this line of code with:
```common = np.result_type(values.dtype, comps_array.dtype)```
 locally.

fyi,
the release note for numpy 1.25.0: https://numpy.org/devdocs/release/1.25.0-notes.html
the deprecation warning of np.find_common_type: https://numpy.org/devdocs/reference/generated/numpy.find_common_type.html#numpy.find_common_type
the documentation to `np.result_type(*arrays_and_dtypes)`: https://numpy.org/devdocs/reference/generated/numpy.result_type.html#numpy.result_type

**Comment by serrayos** [comment]
Thank you @JoshuaGhost. My pandas version is already 2.0.3 and numpy version 1.25.1. Ad I still get the deprecation warning while using osmnx.

**Comment by rwedge** [comment]
From my own testing, upgrading to pandas versions 2.0.2 and higher removes the warnings produced by the code snippet. 

Also, the current release of SDV pins numpy below 1.25 so the deprecation warning won't be encountered.

Closing this as the root issue in pandas has been resolved.

**Comment by FatemehRafiee1** [comment]
@rwedge @JoshuaGhost Thank you, upgrading pandas solved the problem here.
