### ISSUE TITLE
Error defining numerical_distributions with CopulaGANSynthesizer  (`'uniform'`)

### ISSUE THREAD

**Issue by fixative-subtitle** [sdv-dev/SDV#1479]
### Environment Details

* SDV version: 1.2.0
* Python version: 3.9.16
* Operating System: Ubuntu

### Error Description

TypeError when setting a numerical_distributions of 'uniform' using CopulaGANSynthesizer:

`TypeError: Invalid distribution: <class 'copulas.univariate.uniform.UniformUnivariate'>`

### Steps to reproduce

I have three datetime columns with the following metadata:

```
"date1": {
            "sdtype": "datetime",
            "datetime_format": "%Y-%m-%d"`

`},
        "datetime2": {
            "sdtype": "datetime",
            "datetime_format": "%Y-%m-%d %H:%M:%S"
        },
        "datetime3": {
            "sdtype": "datetime",
            "datetime_format": "%Y-%m-%d %H:%M:%S"
```

In the original data these dates are evenly spaced throughout the year so I want to set a uniform distribution:

```
synthesizer = CopulaGANSynthesizer(
    metadata, # required
    enforce_min_max_values=True,
    enforce_rounding=True,
    numerical_distributions={
        'date1': 'uniform',
        'datetime2': 'uniform',
        'datetime3': 'uniform'
        },
    epochs=500,
    verbose=False,
    cuda=True
)
```

However, I receive the following error on synthesizer.fit(real_data)

`TypeError: Invalid distribution: <class 'copulas.univariate.uniform.UniformUnivariate'>`

I have attempted to convert the date columns to numeric timedeltas and I receive the same error.

Otherwise, if I remove the numerical_distributions parameter everything runs fine.

**Comment by npatki** [comment]
Hi @fixative-subtitle, thanks for filing the issue. I can replicate it using the following (made up) dataset:

```python
import pandas as pd

data = pd.DataFrame(data={
    'date1': ['2022-02-01', '2023-06-22', '2021-12-21', '2000-07-20', '2010-09-18'],
    'datetime2': ['2021-09-21 02:03:32', '2023-02-04 12:30:56', '2022-12-09 05:29:35', '2020-03-04 19:12:40', '2023-04-05 05:39:12'],
    'datetime3': ['2020-08-18 12:13:32', '2021-01-04 15:30:56', '2021-11-05 13:45:35', '2021-03-05 20:12:40', '2023-05-05 05:39:12'],
})
```

### Workaround
Until we get the `uniform` distribution to work, you should be able to use the `beta` distribution to achieve something similar. In a beta distribution, if alpha and beta are both 1, it essentially becomes a uniform distribution. Hopefully, the ML model will be able to learn `alpha = beta = 1`.

### Root Cause
It turns out, our pre-processing library (RDT) is not yet setup to work with uniform distributions. We've filed [RDT issue #655](https://github.com/sdv-dev/RDT/issues/655) to add it.

Once it's added, we may need to do more work in the SDV to enable it for CopulaGAN, so we'll keep this issue open until there's a verified fix in the SDV library.

**Comment by lajohn4747** [comment]
Tested with data set provided by @npatki 
Uniform numerical distribution added from [RDT issue #655](https://github.com/sdv-dev/RDT/issues/655)
