### ISSUE TITLE
When leveraging Spark to generate in parallel how to make sure the records are unqiue

### ISSUE THREAD

**Issue by sahoosan** [sdv-dev/SDV#1483]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.2.0
* Python version: 3.8.17
* Operating System: Linux

### Problem description
I am using the Hotels and Guuests example that uses the HMASynthesizer. When generating from one processor worked fine I encountered issues when I try to run using Spark. The idea behind running form Spark is to see if the generation process can scale when I need to generate billions of records.

I tried to generate 100 Hotel records from 5 spark executors asking them to generate 20 each. All 5 of them returned the same 20 records.
How do I make them generate unique records? For example I expect the Hotel_ids in the result be unique with values ranging from HID_000 to HID_099 instead of  HID_000 to HID_019 repeating 5 times.

Thanks
Sanjeeb

**Comment by npatki** [comment]
Hi @sahoosan, nice to meet you! It may be helpful to review the current functionality first.

### Current Functionality
The SDV sampling is designed to generate synthetic data incrementally. For example:

```python
synthetic_data1 = synthesizer.sample(num_rows=100)
synthetic_data2 = synthesizer.sample(num_rows=100)
```

The first call will contain `HID_000` to `HID_099`. The second call will contain `HID_100` to `HID_199`, etc. You can then use [reset_sampling](https://docs.sdv.dev/sdv/single-table-data/sampling/sample-realistic-data#reset_samplinghttps://docs.sdv.dev/sdv/single-table-data/sampling/sample-realistic-data#reset_sampling) to reset to the original state.

```python
synthesizer.reset_sampling()
synthetic_data3 = synthesizer.sample(num_rows=100)
```

Now the synthetic data 3 is the same as the first result -- for the IDs as well as any other columns.

### Next Steps
I'm not very familiar with Spark so I'm not sure how this is being set up. I'm guessing each processor has its own copy of the synthesizer, so each will start from the same state? There is no way to "fast forward" the state at the moment -- but we can consider this a feature request if this will be useful to you. 

I'm curious what your use case is? I assume using the demo guests/hotels dataset is a trial run for something?

**Workaround**: _I haven't verified this, but worth a try._
1. You can try setting random seeds in numpy according to #157. Then, the _data_ columns will be different
2. Unfortunately, you'd have to override the ID columns yourself to prevent duplicates. Maybe each processor can perturb the IDs by some amount?

**Comment by kveerama** [comment]
Hi @sahoosan the workaround mentioned by @sanketahegde probably won’t work for HMASynthesizer as it is not a torch based model. We are checking a few things and will get back to you.

**Comment by npatki** [comment]
Hello all, I'm not sure if you are still working on these projects?

Indeed setting the numpy seed and torch seed would help cover most cases of randomness. However, you may notice some different behavior with primary key IDs.

> Hotel Ids still duplicate with this, though the other columns look good.

For primary keys, the goal is to generate globally unique IDs (a primary key must be unique in the entire table in order to uniquely identify a particular row). If want to sample IDs with Spark parallel, it is a bit difficult to ensure that a Spark cluster does not accidentally create the same ID that another Spark cluster created. 

Some options you may have:
- You can set up each cluster to append a value to the end of the synthesized ID. For example cluster A can append to create `HID_000(a)`, `HID_001(a)`, ... and cluster B can append to create `HID_000(b)`, `HID_001(b)`, etc. This will ensure that when you put all the data together (from all clusters), the values will be unique.
- You can play around with our [pre-processing functions](https://docs.sdv.dev/sdv/single-table-data/modeling/customizations/preprocessing#modifying-the-transformers). It should be possible to assign an AnonymizedFaker that is capable of generating long strings of random values such as UUIDs. When these are randomized, it will be _very unlikely_ to create 2 IDs that collide. If this interests you, let me know and I can provide an example.

**Comment by npatki** [comment]
As this discussion has been inactive for a while, I will close the issue and mark the overall question as answered. But please feel free to reply if there is more to investigate and I am happy to reopen for discussion. Thanks.
