### ISSUE TITLE
Is it possible to generate events based time-series data with SDV?

### ISSUE THREAD

**Issue by prtkkmrsngh** [sdv-dev/SDV#1490]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 1.2.0
* Python version: 3.10
* Operating System: macOS Monterey 12.6.5

### Problem description

Want to generate event based time-series data for example credit card complaints where each complaint id can have four status which gets changed on subsequent dates. Here is my real data trying to train via SDV

Complaint Date | Product | Issue | Channel | Response To Consumer | Complaint ID
-- | -- | -- | -- | -- | --
08/05/23 | Credit card | CCAFGE | Twitter | Open | 868669308
09/05/23 | Credit card | DDBCFF | Fax | In progress | 868669308
10/05/23 | Credit card | ABEACG | Phone | Resolved | 868669308
11/05/23 | Credit card | CEDGDB | Fax | Closed | 868669308
20/05/23 | Credit card | CCAFGF | Twitter | Open | 787647367
21/05/23 | Credit card | DDBCFG | Fax | In progress | 787647367
22/05/23 | Credit card | ABEACH | Phone | Resolved | 787647367
23/05/23 | Credit card | CEDGDC | Fax | Closed | 787647367

Is it possible to generate such type of time-series large data?

### What I already tried

Following commands are generating data but it's random data and not the events based

```
import pandas as pd
from sdv.datasets.local import load_csvs
from sdv.metadata import SingleTableMetadata
from sdv.sequential import PARSynthesizer

metadata = SingleTableMetadata()
metadata.detect_from_csv(filepath=<csv_file_path>)

metadata.update_column(
    column_name='Complaint ID',
    sdtype='id',
    regex_format='[1-9]{9}')

metadata.update_column(
    column_name='Complaint Date',
    sdtype='datetime',
    datetime_format='%d/%m/%y')

metadata.set_sequence_key(column_name='Complaint ID')
metadata.set_sequence_index(column_name='Complaint Date')
synthesizer = PARSynthesizer(metadata)

datasets = load_csvs(folder_name=<csv_folder>)

synthesizer.fit(
    data=datasets['credit_card_complaints']
)

synthetic_data = synthesizer.sample(
    num_rows=8
)

df = pd.DataFrame(synthetic_data)

df.to_csv(<csv_file_path_to_write>)

```

### Output

Complaint Date | Product | Issue | Channel | Response To Consumer | Complaint ID
-- | -- | -- | -- | -- | --
15/05/23 | Credit card | ABEACG | Twitter | Closed | 111111111
14/05/23 | Credit card | DDBCFF | Twitter | Closed | 111111111
14/05/23 | Credit card | CEDGDC | Twitter | Closed | 111111111
14/05/23 | Credit card | ABEACG | Fax | Closed | 111111111
17/05/23 | Credit card | CEDGDC | Twitter | Open | 111111112
16/05/23 | Credit card | DDBCFG | Twitter | Closed | 111111112
18/05/23 | Credit card | ABEACH | Phone | Closed | 111111112
20/05/23 | Credit card | CEDGDC | Fax | Closed | 111111112

**Comment by npatki** [comment]
Hi @prtkkmrsngh, 

While it may be possible to do this with the PARSynthesizer somehow, I think the data is not quite suited for it because there seem to be a lot of independencies for very short sequences. Usually when I see a lot of interdependencies, it makes me wonder if there is another schema representation for the data.

I wonder if you'd have more success expressing this data in a flat representation. My suggestion would be to express this data as a **single table** where each Complaint ID takes up 1 row and includes all the 4 states (open, in progress, resolved, closed). If some states haven't happened, you can always mark the appropriate cells as NaN.

Complaint ID | Product | Open Date | Open Channel | Open Issue | Progress Date | Progress Channel | Progress Issue | ...
-- | -- | -- | -- | -- | -- | -- | -- | --
868669308 | Credit card | 08/05/23 | Twitter | CCAFGE | 09/05/23 | Fax | DDBCFF | ...
787647367 | Credit card | 20/05/23 | Twitter | CCAFGF | 21/05/23  | Fax | DDBCFG | ...
... | ... | ... | ... | ... | ... | ... | ... | ...
999999999 | Credit card | 07/20/23 | Twitter | ZZZZZZ | NaN | NaN | NaN | ...

Now, your table will be single table, and easier to model. You could use a variety of [SDV single table synthesizers](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers) to model it.

Let me know if that helps!

**Comment by npatki** [comment]
Hi @prtkkmrsngh, are you still working on this project? I'm closing the issue since it has been inactive for almost a month.

If there is more to discuss, feel free to reply here and I can always re-open the issue. Thanks!
