### ISSUE TITLE
`Fake Hotels` multi-table demo can't generate 1M rows

### ISSUE THREAD

**Issue by pvk-developer** [sdv-dev/SDV#1492]
### Problem Description

With the `fake_hotels` demo we are not able to generate `1_000_000` samples because the primary key in table `hotels`, `hotel_id`, regex is `HID_[0-9]{3}` which will only allow to generate 1000 unique values. 

### Expected behavior
We could change the regex of `HID` to go from `A-Za-z0-9` and make it `4` characters instead of `3` to have a combination of 14 millions.

### Additional context

This change will help benchmark more precisely `HMASynthesizer` and `HSASynthesizer`.

**Comment by npatki** [comment]
The fix in [RDT 749](https://github.com/sdv-dev/RDT/issues/749) now resolves this issue in a different way: Instead of updating the regex, the transformer itself keeps track of when it's run out of regexes. Then, it continues to create new unique values by appending suffixes such as `(1)`, then `(2)`, ... This way, it will never run out and the user can continue to sample as much as they want.
