### ISSUE TITLE
'dict' object has no attribute 'validate'

### ISSUE THREAD

**Issue by Travisma2233** [sdv-dev/SDV#1502]
### Problem description
I currently want to use my own data to complete Gaussian_Copula. At present, I have set the metadata for my data as shown in the figure. Why is there an error as shown in the figure?
![9ea13bbdf61893f60e84b0abbd7ed93](https://github.com/sdv-dev/SDV/assets/83893812/f2335a2e-e06d-45c0-825a-a76f9b31b0e4)
![image](https://github.com/sdv-dev/SDV/assets/83893812/245f3209-3101-4373-ba68-1630d0c9cbe9)

**Comment by stuartong** [comment]
Did you manage to resolve this? What was the issue?

**Comment by npatki** [comment]
Hi @stuartong, I'm not 100% sure what the issue was but if I had to guess, it was because a Python dictionary object was passed in instead of the SDV Metadata object. In the latest version of SDV, the Metadata object can be created from a dictionary as follows:

```python
from sdv.metadata import Metadata

metadata_object = Metadata.load_from_dict(metadata_dictionary)
```

For more info, see the [Metadata API specs](https://docs.sdv.dev/sdv/reference/metadata-spec).

If you're continuing to run into this error, please file a new issue so that we can take a look. Thanks.
