### ISSUE TITLE
Data Not generated correctly for Categorical Variable

### ISSUE THREAD

**Issue by Mrin7** [sdv-dev/SDV#1561]
Is there a way to specify target variable for which you want to generate data as close to the Original data.
My data has 27 columns, and my target variable is categorical (0,1) in the ratio of 48%-52%.
I used Gaussian Copula Synthesizer and it generated data in ratio 90%-10% corresponding to that target variable.

Can you suggest a way forward?
`

**Comment by npatki** [comment]
Hi @Mrin7, we recently updated the SDV so that it's able to better model discrete columns and the ratios. Can you confirm that you are on the **latest** versions of the SDV library as well as the RDT library (which used for preprocessing)?

```python
import sdv
import rdt

print('SDV version ', sdv.__version__)
print('RDT version: ', rdt.__version__)
```

You are looking for **SDV version 1.4.0** and **RDT version 1.7.0**.

If that looks correct, I would also double-check the **metadata** that you provide. Make sure that the target column is listed as `"categorical"` (not `"numerical"`).

```python
# replace with the name of the target column
TARGET_COL_NAME = 'my_target_column'

metadata.to_dict()['columns'][TARGET_COL_NAME]
```

You are looking for `{ 'sdtype':  'categorical' }`

**Comment by Mrin7** [comment]
Hi Neha, 

I updated the packages to the lates version. 
It’s still treating the data as numerical:
 
{'age': {'sdtype': 'numerical'},
 'balance': {'sdtype': 'numerical'},
 'duration': {'sdtype': 'numerical'},
 'campaign': {'sdtype': 'numerical'},
 'previous': {'sdtype': 'numerical'},
 'default_cat': {'sdtype': 'numerical'},
 'housing_cat': {'sdtype': 'numerical'},
 'loan_cat': {'sdtype': 'numerical'},
 'recent_pdays': {'sdtype': 'numerical'},
 'job_blue-collar': {'sdtype': 'numerical'},
 'job_entrepreneur': {'sdtype': 'numerical'},
 'job_other': {'sdtype': 'numerical'},
 'job_pink-collar': {'sdtype': 'numerical'},
 'job_self-employed': {'sdtype': 'numerical'},
 'job_technician': {'sdtype': 'numerical'},
 'job_white-collar': {'sdtype': 'numerical'},
 'marital_divorced': {'sdtype': 'numerical'},
 'marital_married': {'sdtype': 'numerical'},
 'marital_single': {'sdtype': 'numerical'},
 'education_primary': {'sdtype': 'numerical'},
 'education_secondary': {'sdtype': 'numerical'},
 'education_tertiary': {'sdtype': 'numerical'},
 'education_unknown': {'sdtype': 'numerical'},
 'poutcome_failure': {'sdtype': 'numerical'},
 'poutcome_success': {'sdtype': 'numerical'},
 'poutcome_unknown': {'sdtype': 'numerical'},
 'deposit_cat': {'sdtype': 'numerical'}}
 

It’s treating all the columns as numerical, We have about 20 categorical columns, do I need to update dtype for all 20 of those or just for my target variable : “deposit_cat”.

Is this an issue for other algorithms as well – GTGAN, FAST ML, TVAE?

Best,
Mrin

**Comment by npatki** [comment]
Hi @Mrin7, thanks for sharing. I would recommend updating the metadata for the affected columns.

All SDV synthesizers rely on using the metadata as the ground source-of-truth for what a column represents. So to get the best results, I'd recommend making sure that all columns in the metadata accurately reflect the data.

You should be able to use the [update_column method](https://docs.sdv.dev/sdv/single-table-data/data-preparation/single-table-metadata-api#update_column) to programmatically update columns.

```python
affected_columns = ['A', 'B', 'C', ...] # list affected columns

for column_name in affected_columns:
    metadata.update_column(
        column_name=column_name,
        sdtype='categorical')
```

I would also recommend saving the metadata as a JSON file so that you do not have to do this again.

```python
metadata.save_to_json(filepath='my_metadata.json')

# in the future, you can reload the metadata from the file
metadata = SingleTableMetadata.load_from_json(
    filepath='my_metadata.json')
```

**Comment by Mrin7** [comment]
Thank you so much @npatki . This a very helpful tip. 
I understand that (0,1) can be treated as Boolean, Numerical or Categorical. So, It's better to check metadata and update it.

**Comment by npatki** [comment]
No problem! 

The SDV Synthesizers should be treating boolean and categorical columns similarly -- as discrete variables. However, numerical columns are treated as continuous variables. For all intents and purposes, the (0, 1) values you have _are_ distinct categories, so I'd recommend marking as categorical. 

BTW the topic of categorical vs. numerical can be tricky so we wrote a blog article about it here: https://datacebo.com/blog/categorical-data/

Let us know if that's hlsepful!

**Comment by npatki** [comment]
Hi @Mrin7, I hope your issues have been resolved. I'm closing this issue off since it has been inactive for a few weeks. 

If there is more to discuss, please feel free to reply and I can always reopen. Thanks!
