### ISSUE TITLE
Number of synthesized child rows not as expected?

### ISSUE THREAD

**Issue by amontz** [sdv-dev/SDV#158]
* SDV version: 0.3.2
* Python version: 3.7.6
* Operating System: Linux

### Description

The number of synthesized child rows was address in #83 and modeled in #93, but while experimenting with the AirBnB dataset in the example, I'm getting quite different distributions of the child sessions table compared between the original and synthetic.  

### What I Did
For example
```python
import pandas as pd
from sdv import Metadata, SDV
import matplotlib.pyplot as plt

users_train = pd.read_csv("./data/train_users_2.csv.zip")
sessions = (
            pd.read_csv("./data/sessions.csv.zip")
            .merge(users_train["id"], left_on="user_id", right_on="id")
            .drop("id", axis=1)
)

metadata = Metadata()
metadata.add_table("users_train", data=users_train, primary_key="id")
metadata.add_table("sessions", data=sessions, parent="users_train",
                                  foreign_key="user_id")

tables = {"users_train": users_train, "sessions": sessions}

sdv_ab = SDV()
sdv_ab.fit(metadata, tables)

N = 10000
samps = sdv_ab.sample_all(N)

user_ids = users_train.id.sample(N)
plt.hist([sessions[sessions.user_id.isin(user_ids)].groupby("user_id").size(),
           samps["sessions"].groupby("user_id").size()], bins=100,
           label=["real", "SDV"]);
plt.legend();
```
Results in:

![airbnb_num_sessions](https://user-images.githubusercontent.com/18690511/82512259-26546c80-9ad5-11ea-972f-2cc132aa1738.png)

Is this expected? Or am I doing this wrong?
Thanks.

**Comment by npatki** [comment]
Hi @amontz, some variation between the synthetic and real data is expected. Nothing seems wrong about the usage.

Under-the-hood, the HMA1 algorithm is estimating the observed distribution with a well-known distribution (such as Gaussian, Beta, Gamma, etc.). If your real data doesn't exactly conform to such a distribution, then the SDV will find the next best fit. This seems to be the case here.

Since this issue was filed, we've made some updates to the SDV library. If you're able to run it again, I'm curious whether your results will have changed. If you'd like the ability to control how the number of children are modeled, it would be great to file a new feature request for it.

**Comment by npatki** [comment]
Hello, this issue has been stale for some time now. I'll close it since we've answered your initial questions. If there is more you'd like to discuss, feel free to reply and I'll reopen the issue.
