### ISSUE TITLE
Consistent Generation of Measurement Values and Corresponding Dates

### ISSUE THREAD

**Issue by Ng-ms** [sdv-dev/SDV#1665]
I'm using the PARSynthesizer for generating values and their corresponding dates. In my data, the relationship between these values and dates is always valid: if there's a value, there will be a corresponding date, and if there's no value, there will be a NaN value for the date.

Currently, the PARSynthesizer generates values and dates somewhat inconsistently, which leads to missing pairs of values and dates. I'm requesting a feature that ensures the consistent generation of value-date pairs, where if one is generated, the other should also be generated.

**Comment by npatki** [comment]
Hi @Ng-ms, since this is a hard business rule of something that must be true for _every_ row, an ML model will not necessarily learn this rule out-of-the-box. It will be necessary to write a [constraint](https://docs.sdv.dev/sdv/reference/constraint-logic).

Currently, the PARSynthesizer does not have the ability to accept constraints. A request for this already been filed in #570, so we can continue to use that issue to track progress. I can mark this issue as a duplicate.

As a workaround, you may consider manually modifying your synthetic data afterwards to match the rules that you need. Although I recognize this is cumbersome and may not get you the data quality you need.
