### ISSUE TITLE
Access Noise Vector for When Sampling

### ISSUE THREAD

**Issue by patzingo** [sdv-dev/SDV#1667]
How can I access the noise vector used to generate new samples from the CTGAN?  E.g. when calling 
`synthetic_data = synthesizer.sample(num_rows=10)`

How can I get the 10 vectors used to induce novelty in the samples?  Likewise, is there a way to pass in a fixed noise vectors into the call to sample?

**Comment by npatki** [comment]
Hi @patzingo,

You mention introducing novelty in the samples (synthetic data). By default, the synthesizers are designed to introduce novelty such that every subsequent sample would provide different synthetic data.

```python
# all data samples will be different
synthetic_data1 = synthesizer.sample(num_rows=10)
synthetic_data2 = synthesizer.sample(num_rows=10)
synthetic_data3 = synthesizer.sample(num_rows=10)
...
```

Is this insufficient for your use case? Could you describe what problem you're trying to solve that would require you to accessing or fixing noise vectors? 

Not all the synthesizers necessarily have a noise vector that is easily accessible but perhaps if I can understand more about your problem, I can offer other workarounds.

**Comment by npatki** [comment]
Hi @patzingo, are you still working on this project? I'm closing off the issue since it has been inactive for a few weeks. 

Though please feel free to respond if there is more to discuss and I can always re-open the issue. If it turns out that a noise vector (or some equivalent representation of it) is needed for your usage, then we can file a separate feature request to track it.
