### ISSUE TITLE
HMASynthesizer creates too much synthetic data (always creates a child for every parent row)

### ISSUE THREAD

**Issue by dfosticupgrade** [sdv-dev/SDV#1673]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: `1.5.0`
* Python version: 3.9.6
* Operating System: macOS Ventura 13.6

### Error Description
On a multi-table model, using HMASynthesizer, data will be generated uneven across the tables

My model: 5 tables
Table_A: parent, primary_key = id
Table_B: child, foreign_key = Table_A.id 
Table_C: child, foreign_key = Table_A.id 
Table_D: child, foreign_key = Table_A.id 
Table_E: child, foreign_key = Table_A.id 

Real data:
Table_A:  228 rows
Table_B:   88 rows
Table_C:  188 rows
Table_D:   14 rows
Table_E:    8 rows

### Steps to reproduce

```
real_data = {
    'Table_A': table_a_dataframe,
    'Table_B': table_b_dataframe,
    'Table_C': table_c_dataframe,
    'Table_D': table_d_dataframe,
    'Table_E': table_e_dataframe,
}

synthesizer.fit(data=real_data)
synthetic_data = synthesizer.sample(scale=1.0)
```

for `synthetic_data = synthesizer.sample(scale=X.0)`
please find below results for each scale

```
    	  original_size   scale=1.0   scale=2.0   scale=3.0
Table_A:      288             228       456         684
Table_B:       88             228       456         684
Table_C:      188             291       551         846
Table_D:       14             213       424         863
Table_E:       16             430       862        1298
```

As you can see only parent_table will scale properly

**Comment by npatki** [comment]
Hi @dfosticupgrade thanks for reporting with the detailed stats. That's definitely unexpected. 

To help us replicate the issue, I'm wondering if you are able to provide the metadata schema? Or at the very least, it would be helpful to see how the tables A-E are connected to each other. You can get a barebones visualization using:

```python
metadata.visualize(show_table_details=None, show_relationship_labels=False)
```

**Comment by npatki** [comment]
Hi @dfosticupgrade, an update:

It appears the issue arises in a very specific case: In your dataset, table A has 228 rows while other tables like D or E only have 14-16 rows. It indicates that a significant number of rows in A have 0 children in D/E. The HMA is set up to create at least 1 child row for every parent. Therefore, the sizes of the tables end up larger than expected.

You can see this in action using the [get_cardinality_plot](https://docs.sdv.dev/sdv/multi-table-data/evaluation#get_cardinality_plot) function for some random data I used to replicate.

<img width="942" alt="image" src="https://github.com/sdv-dev/SDV/assets/3227804/6ea56479-f3a8-437d-879e-61e876adbe27">


### Next Steps
This would have to be an algorithmic fix within the HMA itself. Let's use this issue to track the fix. I'm going to re-title it to reflect the new understanding we have.

I don't see many easy workarounds to this. Potentially, you may want to try with a dataset where each parent row (or at least a majority of parent rows) _do_ have at least 1 child, since the HMA is suited to that.
