### ISSUE TITLE
Cannot create custom constraint with foreign key in multi-table

### ISSUE THREAD

**Issue by longngng** [sdv-dev/SDV#1708]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.7.0
* Python version: 3.10.12
* Operating System: Any

### Error Description

In a multi-table setup, if I create a custom constraint on a child_table that involves a foreign key, I get a KeyError during sampling.

### Steps to reproduce
```
from sdv.multi_table import HMASynthesizer
from sdv.metadata import MultiTableMetadata
from sdv.constraints import create_custom_constraint_class
import pandas as pd

# Add constraints
def is_valid(column_names, data):
    return data['foreign_key'] == data['letter'] + '_' + data['number']

def transform(column_names, data):
    new_data = data.drop(['letter', 'number'], axis=1)
    return new_data

def reverse_transform(column_names, data):
    columns = data['foreign_key'].str.split('_', expand=True)
    data['letter'] = columns[0]
    data['number'] = columns[1]
    return data

custom_constraint = create_custom_constraint_class(
    is_valid_fn=is_valid,
    transform_fn=transform,
    reverse_transform_fn=reverse_transform
)

data_1 = pd.DataFrame({
    'key': ['a_1', 'b_2', 'c_3'],
})

data_2 = pd.DataFrame({
    'foreign_key': ['a_1', 'b_2', 'c_3'],
    'letter': ['a', 'b', 'c'],
    'number': ['1', '2', '3'],
    'other': [7, 8, 9]
})

data = {'data_1': data_1, 'data_2': data_2}


metadata = MultiTableMetadata()
metadata.detect_from_dataframes(data=data)
metadata.update_column(
    table_name='data_1',
    column_name='key',
    sdtype='id',
    regex_format='\w_\d'
)
metadata.update_column(
    table_name='data_2',
    column_name='foreign_key',
    sdtype='id',
    regex_format='\w_\d'
)
metadata.set_primary_key(
    table_name='data_1',
    column_name='key'
)
metadata.add_relationship(
    parent_table_name='data_1',
    child_table_name='data_2',
    parent_primary_key='key',
    child_foreign_key='foreign_key'
)

synth = HMASynthesizer(metadata)
synth.add_custom_constraint_class(custom_constraint, 'custom')


id_must_match = {
    'constraint_class': 'custom',
    'table_name': 'data_2',
    'constraint_parameters': {
        'column_names': [],
    }
}

synth.add_constraints([id_must_match])
synth.fit(data)

sampled = synth.sample(1)
```

**Comment by npatki** [comment]
Hi @longngng, unfortunately primary and foreign keys are not supported for custom constraints.

We have added this info to the [custom constraints docs](https://docs.sdv.dev/sdv/reference/constraint-logic/custom-logic) and [FAQs](https://docs.sdv.dev/sdv/reference/constraint-logic/custom-logic#which-types-of-columns-can-i-use-within-a-custom-constraint).

From looking at your code, it seems like the foreign key that you have is a deterministic combination of both the letter and number columns. Since the letter and number columns can be completely recreated from the foreign key, I would consider dropping these columns even before you bring the data into the SDV. You can recreate these columns yourself after you have sampled synthetic data.

**Comment by longngng** [comment]
I see. What if the other columns in data_2 have some more information that I would like to keep? For example
```
data_1 = pd.DataFrame({
    'key': ['a', 'b', 'c'],
})

data_2 = pd.DataFrame({
    'foreign_key': ['a', 'b', 'c, c'],
    'letter': ['a_20231212', 'b_20231213', 'c_20231214', 'c_20231215'],
    'other': [7, 8, 9, 10]
})
```

In this case, I would like to enforce the PK-FK relationship, while using sdtype `timestamp` on the `letter` column after removing the `foreign_key` prefix. Do you have any suggestions for this?

**Comment by npatki** [comment]
In the example above, the easiest solution will be to modify the `'letter'` column so it only contains the values after the foreign key (`'20231212', '20231213', ...`). This would be a standard way to denote a timestamp. Then, it is much easier to model and recreate the column because it has no dependency on any other column. 

I would like to understand your project a bit better though. Why does the `'letter'` column contain the foreign key's prefix? Is this standard practice in the datasets you are working with? Perhaps if I could better understand why the database is set up this way, it will help us come up with a solution.

**Comment by longngng** [comment]
It is just a legacy thing in the dataset I am working with. Thanks for the suggestion!

**Comment by npatki** [comment]
No problem @longngng. Happy to help.

I'm closing this issue off as out-of-scope since constraints were not designed to be working with foreign keys. But if we ever come up with a compelling use case for this -- one that cannot be done by some pre-processing -- then we can always open a new feature request to track.
