### ISSUE TITLE
set_sequence_index documentation is incorrect

### ISSUE THREAD

**Issue by yoid2000** [sdv-dev/SDV#1714]
The documentation on this page: https://docs.sdv.dev/sdv/sequential-data/data-preparation/sequential-metadata-api

Under the set_sequence_index heading

gives as a code example:

`metadata.set_sequence_key(sequence_index='Time')`

Rather it should be this:

`    metadata.set_sequence_index(column_name='Time')`

**Comment by npatki** [comment]
Thanks for letting us know @yoid2000. This should now be fixed in the docs. (May require a refresh to update the cache.)

<img width="954" alt="image" src="https://github.com/sdv-dev/SDV/assets/3227804/755a5e7e-92b3-455e-9687-6e42ed637d9c">

Please feel free to file a new issue if you find other inconsistencies in the docs.
