### ISSUE TITLE
Imbalanced data and conditional sampling

### ISSUE THREAD

**Issue by gnomesanta** [sdv-dev/SDV#1729]
* SDV version: 1.5.0
* Python version: 3.10.11
* Operating System: Sonoma 14.1

### Problem description

Hi, my original dataset is imbalanced on a target column so I am trying to generate a synthetic dataset using conditional sampling. I made two conditions, one for target=0, one for target=1. 

### What I already tried

```
condition_0 = Condition(num_rows=500, column_values={'target-column': 0.0})
condition_1= Condition(num_rows=200, column_values={'target-column': 1.0})

tvae_sample_conditional = tvae_model.sample_from_conditions(conditions=[condition_0, condition_1], max_tries_per_batch=10000, batch_size=1000, output_file_path='sample.csv')
```

I am getting the message below. 
```
The regex generator is not able to generate 5000 new unique values (only (3410+0j) unique value left). Please use 'reset_randomization' in order to restart the generator.
```

I am unsure of how to use the reset_randomization method. 
```
>>> tvae_model.reset_randomization()
AttributeError: 'TVAESynthesizer' object has no attribute 'reset_randomization'
```
Any help appreciated, thanks!

**Comment by npatki** [comment]
Hi @gnomesanta, when you use conditional sampling with a neural network-based synthesizer such as TVAE, it will require many attempts to match the conditions. It appears that you are running out of attempts because a Regex (in your metadata) is limiting the possibilities.

But to confirm this, **would you be able to share your final metadata**? You can do this by printing our metadata or by saving it as a JSON file and attaching it here (recommended approach).

```python
metadata.save_to_json(filepath='my_metadata.json')
```

**Comment by npatki** [comment]
Hi @gnomesanta, are you still running into this issue?

I'm not sure what your metadata looks like so I don't know if this will help: If you have a Regex that is limiting the # of possibilities, you may want to update your metadata to provide a larger Regex.

For eg. the following regex will allow for 1,000 possibilities (`id_000` to `id_999`): `id_[0-9]{3}`. To allow for more possibilities you can either update the allowed characters (`id_[0-9a-z]`) or increase the number of digits (`id_[0-9]{10}`). Do note that we plan to update the defaults in the future so the synthesizer will not crash if it runs out of Regexes (see [RDT issue #749](https://github.com/sdv-dev/RDT/issues/749)).

**Comment by npatki** [comment]
Hi @gnomesanta, are you still working on this project? I'm closing off this issue since it has been inactive for some time and we've discussed one possible cause and suggestion for conditional sampling.

If there is more to discuss, please feel free to reply to this issue and we can always reopen for further investigation. Thanks.
