### ISSUE TITLE
ValueError: Cannot convert float NaN to integer

### ISSUE THREAD

**Issue by ThomasK1018** [sdv-dev/SDV#1730]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.8.0
* Python version: 3.11.5
* Operating System: Mac

### Error Description

I used the following code and the following dataset. Everything was alright yesterday. I tried to amend some of the contents of the datasets and suddenly this error keeps appearing. I reverted everything back to yesterday's version and this error keeps appearing. But there was not a single missing value in the existing dataset. Datasets are also attached for your testing purposes. Thanks.

[ads_dataset.csv](https://github.com/sdv-dev/SDV/files/13783880/ads_dataset.csv)
[feeds_dataset.csv](https://github.com/sdv-dev/SDV/files/13783881/feeds_dataset.csv)
[unique_id.csv](https://github.com/sdv-dev/SDV/files/13783882/unique_id.csv)

### Steps to reproduce

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sdv.datasets.local import load_csvs

datasets = load_csvs(
    folder_name='/Users/thomaskwok/Downloads/SDV_dataset/New Small Dataset',
    read_csv_parameters={
        'skipinitialspace': True
    })



from sdv.metadata import MultiTableMetadata

metadata = MultiTableMetadata()

metadata.detect_from_dataframes(
    data={
        'unique_id': datasets['unique_id'],
        'feeds_dataset': datasets['feeds_dataset'],
        'ads_dataset': datasets['ads_dataset']
}
)

metadata.update_column(
    table_name='unique_id',
    column_name='user_id',
    sdtype='id')

metadata.update_column(
    table_name='feeds_dataset',
    column_name='user_id',
    sdtype='id')

metadata.update_column(
    table_name = 'ads_dataset',
    column_name = 'city',
    sdtype = 'categorical')

metadata.update_column(
    table_name = 'ads_dataset',
    column_name = 'city_rank',
    sdtype = 'categorical')


metadata.update_column(
    table_name='ads_dataset',
    column_name='user_id',
    sdtype='id')


metadata.set_primary_key(
    table_name='unique_id',
    column_name='user_id'
)

from sdv.multi_table import HMASynthesizer

synthesizer = HMASynthesizer(metadata)
synthesizer.fit(datasets)
synthetic_data = synthesizer.sample()
```

**Comment by npatki** [comment]
Hi @ThomasK1018, thanks for the detailed description. We were able to replicate your error. For future reference, I'm attaching the stack trace below.

[stack_trace.txt](https://github.com/sdv-dev/SDV/files/13813948/stack_trace.txt)

### Root Cause
We will investigate more but in all likelihood, this is probably related to #1691. The known bug is that HMA sometimes creates null values even when there aren't any in the real data. Usually this happens for float64 or string types in the child table. In this particular case, you have int64 columns (that are categorical). The int64 storage type does not support null values, hence the crash.

As a next step, the team can investigate more to confirm that the root cause is, indeed, #1691. If so, we will dedupe the issue. We can also do a better job at preventing the crash and instead just returning the null value (even though this is not quite correct). I've filed [RDT issue 747](https://github.com/sdv-dev/RDT/issues/747) to keep track of this.

### Workarounds
Changing the default distribution for each table to `'norm'` seems to solve this issue because it makes the out-of-bounds error less likely. Unfortunately, this may impact the data quality (but at least it won't crash!)

```python
synthesizer = HMASynthesizer(metadata)

for table_name in ['unique_id', 'ads_dataset', 'feeds_dataset']:
  synthesizer.set_table_parameters(
      table_name=table_name,
      table_parameters={
          'enforce_min_max_values': True,
          'default_distribution': 'norm'
      }
  )

synthesizer.fit(datasets)
synthesizer.sample()
```

Do note that the HMA is only meant for smaller datasets though. So even with this workaround in place, you'll still see the performance alert:
```
PerformanceAlert: Using the HMASynthesizer on this metadata schema is not recommended. To model this data, HMA will generate a large number of columns. (1189 columns)


      Table Name  # Columns in Metadata  Est # Columns
0      unique_id                      1           1129
1  feeds_dataset                     26             26
2    ads_dataset                     34             34

We recommend simplifying your metadata schema by dropping columns that are not necessary. If this is not possible, contact us at info@sdv.dev for enterprise solutions.
```

Ultimately, I'd recommend using the [HSASynthesizer](https://docs.sdv.dev/sdv/multi-table-data/modeling/synthesizers/hsasynthesizer) as it's designed to handle larger datasets more robustly. I've confirmed that it works without issue on this dataset (fitting in a few seconds).

**Comment by ThomasK1018** [comment]
Hi Neha, 

Thanks for your reply. That change on default distribution has certainly helped. May I also ask what are the available choices to be filled in for this section? I have also tried inputting truncnorm and the output is different from leaving in blank. So I would like to know if there are more choices for the distribution. Thanks.

Best Regards,
Thomas

**Comment by npatki** [comment]
Hi @ThomasK1018, no problem. For more info, I'd recommend checking our [docs here](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer#parameter-reference). Note that the `default_distributions` sets the shape for all columns but you can override individual columns by using the `numerical_distributions` parameter too.
