### ISSUE TITLE
Remove bumpversion and use bump-my-version

### ISSUE THREAD

**Issue by gsheni** [sdv-dev/SDV#1802]
### Problem Description

- The bumpversion library is not a maintained library and we should switch to using `bump-my-version`.
  - Alternatively, we could also just use Python's native version management (relying on dev's to increment 1 file).

### Expected behavior
- Use `bump-my-version` to version bump sdv.
- Alternatively, just specify the version in 1 location and have `pyproject.toml` read from that location.

**Comment by amontanez24** [comment]
### Technical Details
Make sure the following commands work:
- `bumpversion candidate --no-tag`
This should bump to the next candidate version (eg. 1.1.1.dev0 -> 1.1.1.dev1)
- `bumpversion --no-tag patch`
This should bump to the next patch (eg. 1.1.1.dev0 -> 1.1.2.dev0)
- `bumpversion --no-tag minor`
This should bump to the next minor (eg. 1.1.0.dev0 ->1.2.0.dev0)
- `bumpversion --no-tag major`
This should bump to the next major version (eg. 1.1.0.dev0 -> 2.0.0.dev0)
- `bumpversion release --no-tag`
This should bump to a release version (Eg. 1.2.0.dev0 -> 1.2.0)

Don't run `make bumpversion-patch` or `make bumpversion-release` because those commands merge to stable. Just call bumpversion or bumpmyversion directly
