### ISSUE TITLE
Show an error (or warning) when trying to use a dataframe column as a datetime sdtype when pandas think it's string / object

### ISSUE THREAD

**Issue by srinify** [sdv-dev/SDV#1839]
**Issue**

When reading a dataset into a pandas dataframe, datetime-y columns often end up getting set to Object / 'string' type.

During sdv model fitting, we attempt to infer the datetime string format from analyzing the values. Specifically, it seems like we use `_guess_datetime_format_for_array` from `pandas.core.tools.datetimes` deep in `sdv._utils.py` etc: https://github.com/sdv-dev/SDV/blob/main/sdv/_utils.py#L43

This best-guess approach to trying to reverse engineer the datetime format seems to throw an InvalidDataError for values that are in-fact valid datetime values:

<img width="1186" alt="Screenshot 2024-03-05 at 7 24 52 PM" src="https://github.com/sdv-dev/SDV/assets/801507/ddb52154-76fe-499f-ac7c-6c5e91b80c0c">

If the user manually casts the Object column to datetime using `pandas.to_datetime()`, then this issue isn't encountered / no errors are thrown.

**Reproducing**

- Dataset Download: https://www.kaggle.com/competitions/nyc-taxi-trip-duration/data
- Dataset: `train.csv`
- Column: `pickup_datettime`
- sdv 0.10.0
- pandas 2.0.0

**Potential Solutions**

- We could potentially improve the error message itself
- And / or we could try showing a warning to the user that converting a dataframe column to datetime may be more reliable

**Comment by npatki** [comment]
SDV is designed to be agnostic to storage (in-memory) representation of something such as datetime. The ground source-of-truth that SDV uses to is **metadata**.

So if the data is loaded in as `object`, that's perfectly fine. In many cases, datetime data will be stored in this way due to how a database is ingested into Python. We don't want to have to make anyone convert any/all columns to datetime.

The solution here would be to add a `datetime_format` string to the metadata object itself -- [See API](https://docs.sdv.dev/sdv/reference/metadata-spec/single-table-metadata-json#columns). The format will explicitly teach SDV how to read the value, and SDV will also ensure that the generated synthetic data matches the same format.
