### ISSUE TITLE
Disable to set sequence key manually for other datatypes, which works in demo

### ISSUE THREAD

**Issue by XiaPoppy** [sdv-dev/SDV#1875]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.10.0
* Python version: 3.11.0
* Operating System: M1 Mac

### Error Description

I want to try with a time series table with several sequences from kaggle [dataset](https://www.kaggle.com/datasets/szrlee/stock-time-series-20050101-to-20171231?select=all_stocks_2017-01-01_to_2018-01-01.csv), all_stocks_2017-01-01_to_2018-01-01.csv file. And I want to set the name of stocks to be the sequence keys. Then I got an error because the data type is not ID. But I noticed that the sequence key in the demo([tutorial file](https://colab.research.google.com/drive/1YLk2uwn8yrSRPy0soEeJwu8Hdk_tGTlE?usp=sharing)) is also not an ID.

### Steps to reproduce

download [csv file ](https://www.kaggle.com/datasets/szrlee/stock-time-series-20050101-to-20171231?select=all_stocks_2017-01-01_to_2018-01-01.csv)all_stocks_2017-01-01_to_2018-01-01.csv, and store it under folder stock.

```
from sdv.datasets.local import load_csvs

datasets = load_csvs(folder_name='stock/')
stock_data = datasets['all_stocks_2017-01-01_to_2018-01-01']
stock_data.head(3)
from sdv.metadata import SingleTableMetadata

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(stock_data)
metadata.set_sequence_index(column_name='Date')
metadata.set_sequence_key(column_name='Name')
```
then I got error message:

> InvalidMetadataError: The sequence_keys ['Name'] must be type 'id' or another PII type.

Could you please help me with that? thanks a lot!

Best,
Danyang

**Comment by srinify** [comment]
Hi Danyang!

In our Colab example, if you squint carefully you can actually see that the `sequence_key` we set _is_ in fact a column (`Symbol`) assigned to the `id` sdtype :) 

<img width="583" alt="Screenshot 2024-03-27 at 9 52 19 AM" src="https://github.com/sdv-dev/SDV/assets/801507/c33436e0-97b8-4e0f-94c8-050cd6c1be45">

If you run `print(metadata)` in our notebook, you can see the full output of the metadata:

```
{
    "sequence_key": "Symbol",
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1",
    "sequence_index": "Date",
    "columns": {
        "Symbol": {
            "sdtype": "id",
            "regex_format": "[A-Z]{4}"
        },
        "Date": {
            "sdtype": "datetime",
            "datetime_format": "%Y-%m-%d"
        },
        "Open": {
            "sdtype": "numerical",
            "computer_representation": "Float"
        },
        "Close": {
            "sdtype": "numerical",
            "computer_representation": "Float"
        },
        "Volume": {
            "sdtype": "numerical",
            "computer_representation": "Int64"
        },
        "MarketCap": {
            "sdtype": "numerical",
            "computer_representation": "Float"
        },
        "Sector": {
            "sdtype": "categorical"
        },
        "Industry": {
            "sdtype": "categorical"
        }
    }
}
```

When working with PARSynthesizer, the `id` sdtype doesn't have to map to a column that's a row-level unique identifier. 

**Solution** 

You can use the `update_column()` method to just change the sdtype for the `Name` column in your dataset. Something like the following assuming your SingleTableMetadata object is named `metadata`:

```
metadata.update_column(
    column_name='Name',
    sdtype='id'
)
```

Then when you set the sequence key, it should work.

**Comment by XiaPoppy** [comment]
Thanks for your reply! Function 'update_column()' works for me. But it is somehow weird that when I sample data from the synthesiser, I got numbers but not names in **column Name**. codes and generated data below:

```
from sdv.datasets.local import load_csvs

datasets = load_csvs(folder_name='stock/')
stock_data = datasets['all_stocks_2017-01-01_to_2018-01-01']

from sdv.metadata import SingleTableMetadata

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(stock_data)
metadata.set_sequence_index(column_name='Date')
metadata.update_column(column_name='Name',
    sdtype='id')
metadata.set_sequence_key(column_name='Name')

# create synthesizer
from sdv.sequential import PARSynthesizer

synthesizer = PARSynthesizer(
    metadata,
    #context_columns=['Sector', 'Industry'],
    verbose=True)

synthesizer.fit(stock_data)

#sample
synthetic_data = synthesizer.sample(num_sequences=10)
synthetic_data.head()
```
<img width="801" alt="截屏2024-03-27 16 24 47" src="https://github.com/sdv-dev/SDV/assets/121298988/7811c543-de85-49c8-889a-722ad7d84dfa">

**Comment by srinify** [comment]
The best way to preserve this context for SDV, I would explicitly define the format of the `Name` column when running `update_column()`:

```
metadata.update_column(column_name='Name',
    sdtype='id',
    regex_format= "[A-Z]+"
)
```

When I updated and re-trained the mode, this is the synthetic data that's generated:

![Screenshot 2024-03-28 at 4 08 00 PM](https://github.com/sdv-dev/SDV/assets/801507/57a84165-cc3b-4057-8fed-627548c7139c)

Of course, you can go further and tweak the regex to only generate names with 4 values (or something more nuanced like 3 or 4, etc):

```
metadata.update_column(column_name='Name',
    sdtype='id',
    regex_format= "[A-Z]{4}"
)
```

This is the same "trick" used in the Colab notebook too that you referenced:

![Screenshot 2024-03-28 at 4 09 37 PM](https://github.com/sdv-dev/SDV/assets/801507/d1a5b3c8-b4ac-4064-9e82-8e4c6e43e5b1)

[Relevant docs article](https://docs.sdv.dev/sdv/reference/metadata-spec/sdtypes#id)

**Additional Context**

Under the hood, SDV at some point has to convert every value in your dataset to numerical values since ML models really only interface with numerical values. Then, when you generate synthetic data the values can be mapped back to text, categorical, or other non-numerical values depending on the metadata.

By explicitly defining the `regex_format`, we're making sure to specify that we want SDV to ultimately treat this as & synthesize text (not just give us back the numerical values used under the hood)!
