### ISSUE TITLE
Sub-100% Data Validity

### ISSUE THREAD

**Issue by prupireddy** [sdv-dev/SDV#1899]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.11.0
* Python version: 3.11.7
* Operating System: Windows 10 Enterprise

### Error Description

I have a PAR model running on a health dataset. I noticed that my Data Validity drops from 100% when I include a Days_Supplied feature. The website said to contact you if that occurs. 
[DataValidityIssue.xlsx](https://github.com/sdv-dev/SDV/files/14891145/DataValidityIssue.xlsx)

### Steps to reproduce

I've attached an excel file that has the true values on the left and the synthetic on the right. For privacy reasons, I cannot send the full data and code.

**Comment by srinify** [comment]
Hi there @prupireddy it looks like the reason the score isn't 100% is because the PARSynthesizer model isn't adhering to the min and max values in your original dataset column.

I have 2 questions:

1. When you crafted your SingleTableMetadata object, what `sdtype` was detected or did you assign? You can run `print(your_single_table_metdata_object)` on your machine to look this up and just tell me the one one for this `Days_Supplied` column.

2. Did you set the `enforce_min_max_values` parameter when defining your PARSynthesizer object? Or did you skip this and just left the model use the default value?

**Comment by prupireddy** [comment]
1. Categorical was detected (I didn't assign). The pandas dtype is float64.
2. No I did not; it used the default. 

Thank you

**Comment by npatki** [comment]
Hi @prupireddy and @srinify there is currently a known issue that `PARSynthesizer` specifically has when the column is `categorical` but it is represented in a `float` format. I wonder if this is the root cause? #1910.

I would start by confirming whether this column (`Days_Supplied`) was correctly detected in the metadata, as the detection is not guaranteed to be 100% accurate. Does this column truly represent discrete categories or is it numerical? To help you decide, see [this sdtypes reference](https://docs.sdv.dev/sdv/reference/metadata-spec/sdtypes).

1. If it's supposed to be `numerical`, please update your metadata and try with the updated version. There are currently no known bugs in PARSynthesizer for numerical data.
2. If it's supposed to `categorical`, then you can try the workaround I've listed in #1910.

**Comment by prupireddy** [comment]
Since the true data type was supposed to be categorical, I followed your first suggestion and just hardcoded it to numerical (as opposed to having it get detected which gave categorical). This resolved the issue.

**Comment by npatki** [comment]
Great. Appreciate the confirmation!
