### ISSUE TITLE
NaN values in sampled data for time series data. (using PARSynthesizer)

### ISSUE THREAD

**Issue by XiaPoppy** [sdv-dev/SDV#1907]
there may exist NaN value for Open, High, Low columns in https://github.com/sdv-dev/SDV/issues/1875

![image](https://github.com/sdv-dev/SDV/assets/121298988/7c3ddf32-ce6a-46b8-88f4-35f35a0c5594)

**Comment by npatki** [comment]
Hi @XiaPoppy, thanks for filing this in a separate issue.

All SDV synthesizers are designed to recreate the patterns that are observed in the real data -- including the presence of NaN values. I verified that in the Kaggle dataset you provided (`'all_stocks_2017-01-01_to_2018-01-01.csv'`), there _are_ NaN values present in the `Open`, `High` and `Low` columns. See screenshot below.

![image](https://github.com/sdv-dev/SDV/assets/3227804/000602d3-4e2f-453c-849e-927ca23621c1)

Since there are NaN values in the real data, it is expected for synthetic data to also contain NaN values.  Does that make sense?

Please let me know if you have any additional comments about _why_ these particular NaN values in the synthetic data are incorrect. Thanks.

**Comment by npatki** [comment]
Hi @XiaPoppy, I'm closing this off since we answered the question and I believe you gave a thumbs up :) 

Please feel free to respond if you have any follow-up questions about these NaN values. I can always re-open the issue for investigation. Thanks.
