### ISSUE TITLE
Relational Data with Multiple Foreign Keys

### ISSUE THREAD

**Issue by kvrameshreddy** [sdv-dev/SDV#193]
* SDV version:SDV version:0.4.0
* Python version:3.7
* Operating System:Windows 8.1

### Description

How to generate Relational data as follow using SDV.
I am already using SDV for generating relational data as specified in Readme doc. How to solve the above use case ?
![SDV_Query](https://user-images.githubusercontent.com/49742709/93222991-2fa4cb80-f78d-11ea-95ef-732d94a6e048.JPG)

**Comment by csala** [comment]
Hello @kvrameshreddy 

This is what is called a _multiparent scenario_, which was is supported by SDV since version [v0.3.4](https://github.com/sdv-dev/SDV/releases/tag/v0.3.4), when issue #162 was solved.

For this to work nothing special needs to be done: you just need to create the metadata specifying the relationships:

```python
metadata = Metadata()
metadata.add_table('t1', t1, primary_key='A')
metadata.add_table('t2', t2, primary_key='X')
metadata.add_table('t3', t3, primary_key='P')
metadata.add_table('t4', t4)
metadata.add_relationship(parent='t1', child='t4')
metadata.add_relationship(parent='t2', child='t4')
metadata.add_relationship(parent='t3', child='t4')
```

After this, you can just fit and sample as usual and SDV should take care of it for you.

**Comment by kvrameshreddy** [comment]
Thankyou @csala
