### ISSUE TITLE
Class Imbalances

### ISSUE THREAD

**Issue by bdytx5** [sdv-dev/SDV#1967]
Does class imbalance need to be handled without data before synthesizing new data with synthesizers like the CTGan etc? Also, is there a way to validate the model in order to ensure that it isn't overfitting?

**Comment by srinify** [comment]
Hi there @bdytx5 👋 

**Class imbalance**

SDV's synthesizers were designed to model the patterns in your original data so that they can generate new, representative examples. The synthesizers will usually model the class imbalance (e.g. class `A` is 5% of the rows and class `B` is 95% of the rows) and generate synthetic examples with the same proportions. 

**Overfitting**

I'd highly recommend trying out [GaussianCopulaSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer) as an alternative to CTGANSynthesizer. It's very good at avoiding overfitting, is significantly faster to train, and results in identical model performance / quality.

Even if you decide to stick with CTGANSynthesizer, our data preprocessing step that happens in the background before the model is trained also helps the model overfitting. For example, our [UniformEncoder](https://docs.sdv.dev/rdt/transformers-glossary/categorical/uniformencoder) pre-processes categorical columns into a uniform distribution.

Every time you generate synthetic data, we recommend running through our **evaluation tools** to inspect and understand how the model performed by comparing the synthetic data with the real data.

- [DiagnosticReport](https://docs.sdv.dev/sdv/single-table-data/evaluation/diagnostic) helps validate that basic criteria were maintained
- [QualityReport](https://docs.sdv.dev/sdv/single-table-data/evaluation/data-quality) checks for statistical similarity between your real & synthetic data
- Our [visualizations](https://docs.sdv.dev/sdv/single-table-data/evaluation/visualization) can help you visually understand the model quality as it pertains to different columns

**Comment by srinify** [comment]
Closing out this issue for now since there isn't a clear bug here as far as I can tell! But if you did find a specific bug, please feel free to open a new issue!
