### ISSUE TITLE
pip install takes too long

### ISSUE THREAD

**Issue by Dharmik2510** [sdv-dev/SDV#2001]
Hello,

Earlier I was using:

* SDV version: 0.14.0
* Python version: 3.7
* Operating System: linux

Everything was working fine.

However, I upgraded system to below configs:

* SDV version: 1.12.1
* Python version: 3.10
* Operating System: linux

### Problem description

When executing pip install sdv, torch installation takes 3-4 hours.
I can not let my CI to take this long. Is there any other way I can install sdv quicker ?

**Comment by npatki** [comment]
Hi @Dharmik2510 I see you closed this issue. Does this mean you were able to resolve your problem?

Are you able to share a little more about what the problem was and how you solved it? Your feedback would greatly help anyone else in the SDV community who may be running into a similar issue. Thanks.
