### ISSUE TITLE
How to improve the performance of synthesizers?

### ISSUE THREAD

**Issue by hanzigs** [sdv-dev/SDV#2038]
Hi,
Very good library for synthetic data generation,
I have a dataset, properly transformed with normalization, standardisation, pre-processing, and removed outliers. LGBM and XGB algorithms produce very good F1 score and PRAUC on validation data.
Here is the sample
![image](https://github.com/sdv-dev/SDV/assets/30790120/d83b8eb9-f403-40a8-a681-53598361122f)
Class Distribution is
![image](https://github.com/sdv-dev/SDV/assets/30790120/a1c4077f-8108-4a1a-922d-d9da1444f74b)
I have tried 4 synthesizers
![image](https://github.com/sdv-dev/SDV/assets/30790120/b35e31a3-d6ee-46eb-a427-ce21b202ce87)
I could not improve the real data and generated data similarity, the KS statistics p-value, Jensen-Shannon Divergence, Earth Mover's Distance, PCA Similarity and Cosine Similarity all getting worst values.
Synthesizers used
![image](https://github.com/sdv-dev/SDV/assets/30790120/b1a9242e-a8ba-4adc-9c02-e99e9d997594)
sample model
![image](https://github.com/sdv-dev/SDV/assets/30790120/ffb27a20-278f-4c3c-b0bb-2dd409d8a11a)
Have tried different Epochs
Not sure how to improve? or why it is not working?
Any suggestions please?

**Comment by srinify** [comment]
Hi there @hanzigs my response will be multi-faceted as there's a lot of nuance here!

1. In our experience, we've found that **choosing the right metrics** when evaluating quality of synthetic data is important and also very **strongly tied to your specific use case**. We wrote a [blog post on this exact topic ](https://datacebo.com/blog/how-to-evaluate-synthetic-data/)if you're curious. Depending on the use case and project at hand, you'll pick and optimize for different metrics. It's very challenging to try to optimize for all metrics because there's usually tradeoffs.

2. With that in mind, we actually **don't recommend using p-values** to measure quality. I'd recommend reading our explanation on this topic [here in our docs](https://docs.sdv.dev/sdmetrics/metrics/metrics-in-beta/cstest#faqs) for SDMetrics.

3. Some of our models, like Gaussian Copulas, [are highly tunable](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer#creating-a-synthesizer). You can change the distributions, for example, at the column level. Tuning the SDV synthesizers can go a long way to improving the quality of the generated synthetic data using the metrics from the first part of my response.

**Comment by srinify** [comment]
Hi there @hanzigs hopefully this answer was helpful! I haven't heard from you in 2 weeks so I'm going to go ahead and close this issue out. Feel free to comment and tag me or open a new issue if you have more questions on this front!

**Comment by hanzigs** [comment]
Apologies for the delay, still I'm testing that, I couldn't get expected similarity.
