### ISSUE TITLE
Use of incorrect parameter name in example

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [sdv-dev/SDV#2041]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.13.1
* Python version: 3.11.1
* Operating System:

The positive constraints has the parameter called `strict_boundaries`, but in the example `strict` is given, which results in the error:
![image](https://github.com/sdv-dev/SDV/assets/105622461/b995e22f-794c-47a7-9652-ead6e8dd1809)
![image](https://github.com/sdv-dev/SDV/assets/105622461/d1448003-e602-48f0-b418-5e9ecec7f018)
![image](https://github.com/sdv-dev/SDV/assets/105622461/5b2fadef-adf1-4997-a3b1-828dc75a87a5)

**Comment by npatki** [comment]
Hi @Burhanuddin-Nahargarwala thanks for filing the issue.

Seems like this is actually an issue in our [documentation for this constraint](https://docs.sdv.dev/sdv/reference/constraint-logic/predefined-constraint-classes/positive). Please use the keyword `'strict_boundaries'`, not `'strict'`.

Note that the parameters are listed correctly at the top of the docs page -- it is just the example that's incorrect. We will update the example in the docs. 

<img width="948" alt="image" src="https://github.com/sdv-dev/SDV/assets/3227804/83977a0d-a943-427b-9868-16d596df96fe">

### Do you need a Positive constraint?
To re-surface our message from Slack: By default, SDV synthesizers will enforce that all the synthetic data will adhere to the same min/max boundaries as observed in the real data. This means that as long as your real data has values >=0, then the synthetic data will as well — no constraint is needed

I realize you are adding the constraint _just in case_ there end up being negative values (because you want to know when this happens). If at all possible, I would recommend performing such a check yourself before using SDV. Constraints are only meant to be used if you don't have any other options available -- as adding them may impact performance and quality in different ways.
