### ISSUE TITLE
balance the dataset while synthesizing new data

### ISSUE THREAD

**Issue by yairdata** [sdv-dev/SDV#212]
is there an option to specify the ratio by a specific label ?the use case is for fraud detection so i want the lines of the fraud label to be upsampled because of the imbalance dataset in hand.

**Comment by yairdata** [comment]
thanks @csala  ,i looked at the link [here](https://sdv.dev/SDV/user_guides/single_table/constraints.html#defining-constraints) but couldn't understand how to create rows just based on the minority class, it looks like the transform and reject_sampling are based on column values , do you mean implement some kind of filter mechanism so the data synthesize will be just for the minority class ?
can you share some example of that?

**Comment by gentrexha** [comment]
> thanks @csala ,i looked at the link [here](https://sdv.dev/SDV/user_guides/single_table/constraints.html#defining-constraints) but couldn't understand how to create rows just based on the minority class, it looks like the transform and reject_sampling are based on column values , do you mean implement some kind of filter mechanism so the data synthesize will be just for the minority class ?
> can you share some example of that?

Did you manage to implement a version of this?

**Comment by npatki** [comment]
Update: The preferred solution for this is to use [conditional sampling](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html#conditional-sampling). You can create a condition with a specific label value. The model will synthesize the rest of the row for that value.

So to balance a dataset, you'd create a condition object for the minority class. You can generate as many minority class labels as you need and add them to the real data.

I'll close this issue off since we now support the use case and the issue is stale. Feel free to re-open if there is more to discuss.
