### ISSUE TITLE
Unbalanced synthetic data with Uniform Encoder in child table with HMASynthesizer

### ISSUE THREAD

**Issue by mparentClaraVista** [sdv-dev/SDV#2138]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: 1.14.0
* Python version: 3.11.6
* Operating System: Windows 10.0.22631

### Error Description
Hi everyone. I am trying to synthesize a database with a parent table for customers and a child table for sales. I am having issues with variables that are synthesized with the UniformEncoder() in my child table for sales.

For example, I have a variable for weekday. The real proportion is:

Saturday: 0.273945
Friday: 0.164367
Wednesday: 0.162567
Thursday: 0.144571
Monday: 0.123575
Tuesday: 0.117576
Sunday: 0.013397
However, the synthetic data is completely unbalanced: Sunday and Monday represent almost 90% of sales in the synthetic data, even though they only represent 13% in reality.

Worst still, **the proportion in the synthetic data changes if we shuffle the data before fitting and sampling**. I tried a few shuffles, and **it seems that the first and last modalities that appear in the real data are the ones that are overrepresented compared to the other five.**

Note: I don't have these problems with the UniformEncoder for variables in the parent table.

### Metadata & Code
```
{
    "tables": {
        "customers": {
            "columns": {
                "customer_id": {
                    "sdtype": "id"
                },
		"gender": {
                    "sdtype": "categorical"
		
            },
            "primary_key": "customer_id"
        },
        "sales": {
            "columns": {
                "transaction_id": {
                    "sdtype": "id"
                },
                "customer_id": {
                    "sdtype": "id"
                },
                "weekday": {
                    "sdtype": "categorical"
                },
                "week": {
                    "sdtype": "categorical"
                },
		"year": {
                    "sdtype": "categorical"
                },

                "turnover": {
                    "sdtype": "numerical"
                },
                "quantity": {
                    "sdtype": "numerical"
                }

            }
        }
    },
    "relationships": [
        {
            "parent_table_name": "customers",
            "child_table_name": "sales",
            "parent_primary_key": "customer_id",
            "child_foreign_key": "customer_id"
        }
    ],
    "METADATA_SPEC_VERSION": "MULTI_TABLE_V1"
}

```

I run this code :
```
synthesizer = HMASynthesizer(metadata)
synthesizer.fit(real_data)

scale=1
synthetic_data = synthesizer.sample(scale)
```

real_data is a dictionnary with real dataframes _customers_ & _sales_.

**Comment by npatki** [comment]
Hi @mparentClaraVista, nice to meet you. We appreciate you including all the detailed coding examples and output information.

It appears to me that the issue is not in UniformEncoder but rather the way that HMA is running on your dataset. HMA is designed to exhaustively compute all the intertable patterns, and our experiments have shown that this can come with a tradeoff: The quality of individual tables (particularly the child table) may be worsened. 

[This recent blog post](https://datacebo.com/blog/multi-table-synthesizers/) is is very much related to the above points. Any other differences you are observing with respect to shuffling is likely due to randomness. (The randomness is likely exaggerated by HMA.)

I've personally observed the quality suffers more when there is a low branching factor (eg. if each customer has only 1-2 sales). Is this the case with your data? For higher branching factors (eg. each customer has 100+ sales), HMA has tended to perform better.

### HSA may be a better choice
Other multi-table algorithms such as HSA do not have this issue. This may be a better option for your dataset (though I recognize that you will need to purchase SDV Enterprise to use it).

Based on your metadata and description, I took the liberty to create some random data with the `weekday` column fixed to your proportions. Though I could not replicate your case exactly with HMA, I was able to confirm that **HSA produces higher quality data** (compare screenshots below).

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/5632f82b-e427-45a3-8f17-b22f16c808dd">
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/31b5e7df-c38c-4dc8-a363-7bad39d4856d">

**Comment by npatki** [comment]
Hello, I'm closing off this issue since it's been inactive for a few weeks and we've answered the question. Unfortunately, there is not much more we can do with HMA for this type of behavior. Please feel free to reply if there is more you'd like to discuss around this topic -- I can always reopen the issue to investigate. Thanks.
