### ISSUE TITLE
Column giving single value

### ISSUE THREAD

**Issue by mahmoudibrahim98** [sdv-dev/SDV#216]
* SDV version:
* Python version:
* Operating System:

### Description

We are writing a paper about synthetic data and one of the synthesizers we use is SDV. 
I'm trying to use SDV on Pima Indians Diabetes Database found on https://www.kaggle.com/uciml/pima-indians-diabetes-database. 
When I use the full dataset, the Outcome column give desired output (0 and 1).
However, when I use a 70% partition from the data splited using the train_test_split of scikit, the Outcome column gave only one value which is 0. The output is wrong and can't be used for machine learning training later on.

### What I Did

when i run GaussianCopula on the orginal data:
![image](https://user-images.githubusercontent.com/73237782/96729722-21665280-13be-11eb-9939-86fbf6c8a833.png)
when i run GaussianCopula  on the partitioned data:
![image](https://user-images.githubusercontent.com/73237782/96729837-40fd7b00-13be-11eb-86f9-f1d3de519ba8.png)

**Comment by csala** [comment]
Hi @mahmoudibrahim98 my guess is that the model is learning the Outcome as an integer variable (which is internally generated as an integer and then rounded), and depending on the how the Outcome values were distributed in the train_test split, the generated values may be too likely to be rounded to 0 instead of 1.

You can make things easier for the model by:
* using stratification when making the `train_test_split`
* indicating it that the `Outcome` variable is categorical using the `field_types` argument
* using the `categorical_fuzzy` transformer, which tends to work better for binary categoricals

So, altogether, this should give you much better results:

```python
train, test = train_test_split(data, test_size=0.7, stratify=data['Outcome'])

gc = GaussianCopula(
    field_types={
        'Outcome': {'type': 'categorical'}
    },
    categorical_transformer='categorical_fuzzy',
)
gc.fit(train)
gc.sample()
```

Additionally, since all of the values in this table are positive and some have exponential distributions, you might want to [manually enforce the distribution for certain columns](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html#setting-distributions-for-indvidual-variables)

**Comment by mahmoudibrahim98** [comment]
Hello csala!
Thanks for your reply.
your suggestion solved the issue regarding the Outcome column.

You also suggested manually enforcing distributions for certain columns. My question is doesn't GaussianCopula by default select the optimal univariate distribution? if yes then why do we need to select manually?

**Comment by csala** [comment]
> You also suggested manually enforcing distributions for certain columns. My question is doesn't GaussianCopula by default select the optimal univariate distribution? if yes then why do we need to select manually?

Yes, it does, and in most cases it does a good job at it. But there are some cases where it is not able to find the ideal one. The typical example are the variables that behave like an Exponential, which sometimes the GaussianCopula confounds with the higher end of a Gaussian, which later on ends up sampling negative values. In these cases, forcing a `gamma` on the column gives better results.

By the way, please feel free to [join our slack workspace](https://join.slack.com/t/sdv-space/shared_invite/zt-gdsfcb5w-0QQpFMVoyB2Yd6SRiMplcw) so you can ask these questions there and stay up to date with news and announcements!

**Comment by csala** [comment]
Closing this, as the question has already been responded.
