### ISSUE TITLE
Data is not valid for the 'ScalarRange' constraint error when narrow range

### ISSUE THREAD

**Issue by jalr4ever** [sdv-dev/SDV#2216]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

- SDV version: 1.16.1
- Python version: 3.8.19
- Operating System: macOS Sonoma 14.5 (M3 MAX)

### Error Description

I am testing the ScalarRange constraint for this multi-table and singe-table, and I found that when applying this constraint, the model training throws an error.

```python
  File "/app/miniconda3/envs/sdv-tool-example/lib/python3.8/site-packages/sdv/single_table/base.py", line 391, in _preprocess
    self.validate(data)
  File "/app/miniconda3/envs/sdv-tool-example/lib/python3.8/site-packages/sdv/single_table/base.py", line 204, in validate
    self._validate_constraints(data)
  File "/app/miniconda3/envs/sdv-tool-example/lib/python3.8/site-packages/sdv/single_table/base.py", line 162, in _validate_constraints
    raise ConstraintsNotMetError(errors)
sdv.errors.ConstraintsNotMetError: 
Data is not valid for the 'ScalarRange' constraint:
  checkout_date
2   19 Sep 2020
4   10 Apr 2020
5   19 Oct 2020
6   24 Nov 2020
7   08 Mar 2020
+613 more
```

### Steps to reproduce

[guests.csv](https://github.com/user-attachments/files/16940557/guests.csv)

```python
import pandas as pd
from sdv.metadata import SingleTableMetadata
from sdv.evaluation.single_table import evaluate_quality, run_diagnostic
from sdv.single_table import GaussianCopulaSynthesizer
from datetime import datetime

diagnose = False
export = False
file_name = '../datasets/guests.csv'
current_time = datetime.now().strftime("%Y%m%d%H%M%S")
file_output_name = f'{file_name}_{current_time}_GaussianCopula_gen_synthetic.csv'

real_data = pd.read_csv(file_name)
print(real_data.head(10))

# Create metadata
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(real_data)

# fit model
synthesizer = GaussianCopulaSynthesizer(metadata)
my_constraint = {
    'constraint_class': 'ScalarRange',
    'constraint_parameters': {
        'column_name': 'checkout_date',
        'low_value': '28 Dec 2020',
        'high_value': '31 Dec 2020',
        'strict_boundaries': False
    }
}
synthesizer.add_constraints([my_constraint])
synthesizer.fit(real_data)
```

**Comment by jalr4ever** [comment]
I'm a bit confused about the design of ScalarRange. From my understanding, it should set a range, and then one of the columns in the generated simulation data would fall within that range. However, based on actual operation, it doesn't seem to work that way at all; I find it completely unusable. Am I using it incorrectly?

```python
synthesizer = GaussianCopulaSynthesizer(metadata)
my_constraint = {
    'constraint_class': 'ScalarRange',
    'constraint_parameters': {
        'column_name': 'room_rate',
        'low_value': 156.23,
        'high_value': 139.46,
        'strict_boundaries': False
    }
}
synthesizer.add_constraints([my_constraint])
```
error:

```python
 File "/app/miniconda3/envs/sdv-tool-example/lib/python3.8/site-packages/sdv/single_table/base.py", line 204, in validate
    self._validate_constraints(data)
  File "/app/miniconda3/envs/sdv-tool-example/lib/python3.8/site-packages/sdv/single_table/base.py", line 162, in _validate_constraints
    raise ConstraintsNotMetError(errors)
sdv.errors.ConstraintsNotMetError: 
Data is not valid for the 'ScalarRange' constraint:
   room_rate
0     156.23
1     139.43
2     403.33
3     140.61
4     197.41
+653 more

```

**Comment by jalr4ever** [comment]
I feel like I've figured it out. The predefined logic provided by SDV is a supplementary description of the user’s business data rules, which is why the document mentions that some models have already learned and need to be specified.

So here comes the question: in what scenarios are these custom constraints useful? Besides FixedCombinations, it seems like the other constraints aren't really useful at all?

**Comment by npatki** [comment]
Hi @jalr4ever, your understanding is correct. Constraints are meant to encode business rules that every row in your data *must* follow in order to be valid. This means that constraints must be met by every single row in your real data as well. Or to put another way: A constraint is a description of your data today, not a wish for what you want the synthetic data to be. (For the latter, you can look into [conditional sampling](https://docs.sdv.dev/sdv/single-table-data/sampling/conditional-sampling)).

> So here comes the question: in what scenarios are these custom constraints useful? Besides FixedCombinations, it seems like the other constraints aren't really useful at all?

A custom constraint is one that you define yourself. Do you mean _predefined_ constraints?

- By default, most synthesizers will enforce min/max values, so Positive, Negative, ScalarInequality, and ScalarRange likely aren't needed. But if you ask the synthesizer to turn off min/max value enforcement overall, you would need to add these constraints for select columns that still require hard min/max boundaries.
- I would argue that *all* other predefined constraints are useful if your data contains this kind of logic, and you want 100% of rows to adhere to specific logic. 

It may be the case that your particular data doesn't have any additional logic, in which case you do not need to apply any constraints. Let us know if you have a question about a specific constraint.

**Comment by jalr4ever** [comment]
@npatki OK, tanks for your reply.
