### ISSUE TITLE
Time Series experiment - odd visuals

### ISSUE THREAD

**Issue by andrewcztrack** [sdv-dev/SDV#243]
@csala  and team!

I hope you are all well.

Im getting some strange values on the below time series experiment.

```Python
from sdv.timeseries import PAR
data2 = yf.download("QUAL.AX, QLTY.AX, VGS.AX, VAS.AX, VAE.AX, VISM.AX", start="2019-01-01", end="2020-12-30")['Adj Close'].dropna()

model = PAR()

model.fit(data2)
new_data = model.sample(1)

new_data

new_data.plot()

data2.plot()
```

The plots are not really that close am I missing an option?

**Comment by csala** [comment]
Hi @andrewcztrack!

I'm afraid I'm not completely sure about what you mean by "not really that close". Bear in mind that you are generating a synthetic sample, which should have similar properties to the original data, but at the same time be different from it.

One thing that I can advance is that in most cases it might be a good idea to increase the number of epochs of the model, because sometimes the default value may not be enough. As always, the default value tries to keep a good balance between getting some results and at the same time not taking too much time, but sometimes this value may not be enough and needs to be increased.

As an example, I ran your code snippet increasing the value to 3000 and I even get an example of a stock market bump which consistently spreads across multiple tickers in a specific date:

![image](https://user-images.githubusercontent.com/6129283/98988707-53d01f00-2528-11eb-8da1-d7e768917788.png)
