### ISSUE TITLE
How to generate synthetic data for columns like Name & Address?

### ISSUE THREAD

**Issue by abhisheknagar1983** [sdv-dev/SDV#265]
* SDV version: 0.4.5
* Python version: 3.7
* Operating System: Linux RHEL 

### Description

If we want to generate data which has free format text like (Name and Address) .
How should we define?

As Categorical? Might be a bad idea from performance and privacy point of view.
Kindly advise.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by abhisheknagar1983** [comment]
Current Implementation with Personally Identifiable Information (PII) as True uses faker and generate the data, irrespective of training data set. For Example if my train data set is having all the address for BE, but its generates data for US city address. Can we control this behaviors  (by using some parameter)?

**Comment by npatki** [comment]
The requested functionality has been released since this issue was filed.

> If we want to generate data which has free format text like (Name and Address) . How should we define?

 Use the `anonymize_fields` to map the column name to its anonymization function

> if my train data set is having all the address for BE, but its generates data for US city address. Can we control this behaviors (by using some parameter)?

Yes, newer version of the SDV include a `locales` parameter that you can use to control the anonymized fields.

For more details, see [this discussion](https://github.com/sdv-dev/SDV/discussions/667)


I'll close off the issue since it hasn't been active for some time.
