### ISSUE TITLE
field_distributions column containing NaN's 

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#317]
When using `GaussianCopula`, if the `field_distributions` parameter is set to a column containing NaN's it gets ignored. The code below reproduces this error:

```python3
from sdv.tabular import GaussianCopula
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'x': 0.0, 0.1, 0.5, np.nan, 1.0, 5.0
})

model = GaussianCopula(
    field_distributions={
        'x': 'gamma'
    }
)
model.fit(data)
print(model._field_distributions)
```

Which prints `{'x': <class 'copulas.univariate.gamma.GammaUnivariate'>, 'x#0': Univariate, 'x#1': Univariate}`.

The issue seems to be that the column containing NaN gets transformed into two columns, `x#0` for the actual values and `x#1` for an indicator value describing whether the values are NaN, and these columns are not copying the `field_distributions` parameter.

When working on this, maybe it should also check that the user doesn't specify columns that do not exist in the table, since that would've caught this error.

**Comment by npatki** [comment]
I re-ran this code snippet on the latest version of the SDV (0.15.0). The names of the columns have changed. It's now `x`, `x.is_null` and `x.value`.

```python
>>> model._field_distributions
{'x': copulas.univariate.gamma.GammaUnivariate,
 'x.is_null': copulas.univariate.truncated_gaussian.TruncatedGaussian,
 'x.value': copulas.univariate.gamma.GammaUnivariate}
```

I think we can close the issue since `x.value` is correctly being set to `Gamma`.

The question of what `x.is_null` should be seems like a separate one. Presumably when a user is setting `x` to `Gamma`, they intend to communicate that the non-missing values of `x` are `Gamma`; they are not making any statements about the missing values.
