### ISSUE TITLE
Injection additional data into SDV sampler?

### ISSUE THREAD

**Issue by kmcmearty** [sdv-dev/SDV#320]
I have transactional data from an online webstore where customers put multiple items in their basket. There could a dozen or more items in each transaction / basket. Each row / item purchased in my table is represented by one `transaction_id` and one `item_id`.

I want to create synthetic data from my original dataset but I have many more items in my catalog that are not present in the transactional data. I would like SDV to analyze the current transactional dataset that I have but also inject additional `item_id`'s from my catalog that are not otherwise present in the original dataset.

Would this be possible with a constraint? `from sdv.constraints import ColumnFormula`
I was also wondering about using Single Table Metadata like the Relational Table: `from sdv import Metadata`, but as of now the Single Table Metadata feature is coming soon! https://sdv.dev/SDV/user_guides/single_table/table_metadata.html

Any suggestions? Is this possible to accomplish?

**Comment by csala** [comment]
Hi @kmcmearty this is an interesting use case.

I think that you would probably need to go a bit further than the constraints in order to solve this, but the exact approach may vary depending on the type of data that you are using. Is this being applied to a relational dataset, or to single table data?

**Comment by npatki** [comment]
Update -- the ability to fake entirely new, unseen data is currently out-of-scope for the open source SDV.

> I have many more items in my catalog that are not present in the transactional data

The SDV models are focused on learning from the real data during machine learning and replicating those patterns in the synthetic data. If some items are not present in the real data, then the models will not be able to learn anything about them. Eg. they would have no way to to know what other values are correlated with the unseen items.

There are two workarounds you can use:
1. If you have private or sensitive data, the SDV does not learn the trends at all and simply generates new values from scratch. For more info, check out [this discussion](https://github.com/sdv-dev/SDV/discussions/667).
2. You can simply override the synthetic values with new ones at the end. Of course, you'd be throwing some mathematical correlations in doing so.

Since this question is stale (>1 year old), I'll close it off. If you'd to continue discussion, I'd recommend filing a new feature request or reaching out to our Slack.
