### ISSUE TITLE
Why are some single table metrics not available in the evaluate function?

### ISSUE THREAD

**Issue by nachonavarro** [sdv-dev/SDV#327]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version: 0.7.0
* Python version: 3.8
* Operating System: MacOS 11

### Problem description

I'm trying to run some metrics (but not all) on a synthetic/original dataset that is a single table
but SDV says some of the single-table metrics on the [docs](https://sdv.dev/SDV/user_guides/evaluation/single_table_metrics.html) are not actually single-table.
See the example below

### What I already tried

Steps to reproduce:

```python
from sdv.metrics.demos import load_single_table_demo
from sdv.evaluation import evaluate
evaluate(synthetic_data, real_data, metrics=['BNLikelihood'], aggregate=False)

# throws ValueError: Unknown single-table metric: BNLikelihood
```

I thought BNLikelihood was a single table metric? Am I missing something?
Thanks!

**Comment by csala** [comment]
Thanks for reporting this @nachonavarro This is actually an error on SDMetrics. What happens is that `SingleTableMetric.get_subclasses()` is not returning `BNLikelihood` because it has a subclass (`BNLogLikelihood`), and `evaluate` filters such classes out.

I'll open an issue on SDMetrics to fix this.

Meanwhile, if you want to apply BNLikelihood or any other metric you can do so by importing `sdmetrics` directly and passing the metrics to `sdmetrics.compute_metrics`. Notice that here you need to pass the metrics as a `dict`, and that the order of arguments changes a bit from `evaluate`:

```python
In [1]: from sdv.metrics.demos import load_single_table_demo

In [2]: real_data, synthetic_data, metadata = load_single_table_demo()

In [3]: import sdmetrics

In [4]: metrics = {
   ...:     'BNLikelihood': sdmetrics.single_table.BNLikelihood,
   ...:     'KSTestExtended': sdmetrics.single_table.KSTestExtended,
   ...: }

In [5]: sdmetrics.compute_metrics(metrics, real_data, synthetic_data, metadata)
Out[5]: 
           metric                                     name     score  min_value  max_value      goal
0    BNLikelihood               BayesianNetwork Likelihood       NaN        0.0        1.0  MAXIMIZE
1  KSTestExtended  Inverted Kolmogorov-Smirnov D statistic  0.839412        0.0        1.0  MAXIMIZE
```

In this case `BNLikelihood` returns a `NaN` because the demo data has null values which it does not support, but this approach should allow you to reach any metric you need.

Also, if you want to know where the `NaN` came from, you can also see the exact error by running the metric directly:

```python
In [6]: sdmetrics.single_table.BNLikelihood.compute(real_data, synthetic_data, metadata=metadata)
---------------------------------------------------------------------------
...
ValueError: Chow-Liu tree learning does not current support missing values
```

**Comment by csala** [comment]
An issue was opened in SDMetrics to fix this, so this can be closed: https://github.com/sdv-dev/SDMetrics/issues/54
