### ISSUE TITLE
Publish package to conda-forge

### ISSUE THREAD

**Issue by LihuaXiong2020** [sdv-dev/SDV#345]
### Problem Description

Trying to build SDV package with other dependencies coming from conda-forge but ran into incompatibilities.

### Expected behavior

Publish SDV package to conda-forge so that it can be made compatible with other libraries.

**Comment by csala** [comment]
Hi @LihuaXiong2020 would you mind providing some more details about what the incompatibilities are?

It would help if you can paste the output from the installation command.

I suspect that the problem is not really about the package being in `sdv-dev` instead of `conda-forge`, but rather the dependency versions that are listed in our `meta.yaml`.

**Comment by LihuaXiong2020** [comment]
Hi @csala, the issue is that package dependencies with other libraries in `conda-forge` would be so much easier to resolve when `sdv-dev` also sits there. Do you think it valuable to publish `sdv-dev` in `conda-forge` too, as it's a widely adopted public packaging channel for security and governance reasons?

**Comment by katxiao** [comment]
Hi @LihuaXiong2020, `sdv` is now on `conda-forge`! Please feel free to use the package [here](https://anaconda.org/conda-forge/sdv).
