### ISSUE TITLE
Using an external data loader

### ISSUE THREAD

**Issue by EgorKraevTransferwise** [sdv-dev/SDV#412]
Hi!

I would like to train the models (primarily TVAE and PAR) against rather large datasets (tens of millions of points). 

The assumption of all the APIs is that data is supplied via a pd.DataFrame, which greatly limits the size of data one can work with. In addition, PAR doesn't even include a batch_size argument as best I can tell, so can only be trained on tiny datasets.

How hard would it be to use both models with an externally supplied data loader, that for example returned a dataframe on every iteration (or to save Pandas overhead, even something like Dict[str, np.ndarray] ? )

Many thanks!

**Comment by npatki** [comment]
Hi @EgorKraevTransferwise, nice to meet you.

One of the challenges it that the SDV models aren't set up for incremental training right now. It's necessary to load all the data at once since the models need to use it all at once.

We have an ongoing thread about this. I'll close this issue off in favor of of #805. Feel free to respond there with any feedback or ideas.
