### ISSUE TITLE
Ability to Add Reject Sampling Constraints After Training an SDV Generator

### ISSUE THREAD

**Issue by Oufattole** [sdv-dev/SDV#424]
### Problem Description

After initializing an SDV model, like `GaussianCopula` for example, a user is not able to add rejection-sampling constraints.

### Expected behavior
Users often train a model and then they may want to add different types of rejection sampling constraints to sample certain kinds of data. Currently a user has to manually create a function to reject samples (which is inconvenient and prone to error) or has to reinitialize and train the sdv model with the new desired constraint (retraining can be time consuming for a large dataset).

It would make sense for a user to be able to add rejection-sampling constraints after they have trained their model. This is because the process of training any of the sdv generators is independent of rejection sampling. For example, look at the GaussianCopula `_fit` function:
https://github.com/sdv-dev/SDV/blob/f6fa698bd244bc92887ff601c6c9d99780bfa935/sdv/tabular/copulas.py#L265-L283
Fitting the `copulas.multivariate.GaussianMultivariate` has no dependence on rejection sampling constraints as those are only applied by the post-training `_sample` function. `copulas.multivariate.GaussianMultivariate` has it's own sampling function that has no input for constraints:
https://github.com/sdv-dev/Copulas/blob/dfe3bb9cc035c8d4880724db69c86e749178e65b/copulas/multivariate/gaussian.py#L85-L91
### Additional Context
If you checkout the `handling_constraints` tutorial:
https://github.com/sdv-dev/SDV/blob/master/tutorials/single_table_data/05_Handling_Constraints.ipynb
it's clear that there are two constraint strategies, `Transform Strategies` and `Rejection-Strategies` (the rejection sampling I've been referring to). The only constraints that do affect the training of the generators are `Transform Strategies` as they change the columns we input for the `fit` function. So it makes sense only for those types of constraints to be immutable after initialization.

Users do have the ability to conditionally reject samples after training using the conditions parameter: `model.sample(num_sample, conditions)`, but this only allows users to select specific values to constrain a set of columns to, it does not allow for more flexible constraints such as setting an upper bound or a lower bound, see the tutorial for the info I read for using conditioning:
https://github.com/sdv-dev/SDV/blob/master/tutorials/single_table_data/01_GaussianCopula_Model.ipynb

**Comment by npatki** [comment]
Thank you for the detailed explanation! I follow the logic, and we can follow up with this change for future releases.

In the meantime, I'd love to understand more about your use case & how the need arose to add more reject sampling. To the extent that you're able to share, I'm curious about process you followed when fitting your model.

Some detailed Qs:

- How long is it taking to fit your data? Would you say that time is a pain point when iterating on the model?
- Can you describe a little more about the constraints you wanted to add after modeling? I can imagine two scenarios:
- (a) There is a strict constraint that all the data needs to follow in order to be valid (for eg `age > 0`). You assumed the model would learn this. However, you realized after fitting that this isn't the case, so you need to go back and add them
- (b) The model synthesized data just fine. However, for your particular use case, you wanted to test out different hypothetical scenarios or modifications (eg. _"what if all the ages were >30, even if this isn't the case in the real data"_). So you wanted to play around with different reject sampling.

I'm distinguishing between the two scenarios because I think (b) is technically a conditional sampling use case while (a) is constraints, even though both can be handled through reject sampling.

Any more details or explanation of your process would help us prioritize this!

**Comment by Oufattole** [comment]
So for my use case, initially it took multiple days to train a model. Then we used column transformations to fix this. Some columns were being treated as one hot vectors when instead we wanted them to be treated as labels. Once we fixed this the training takes around 15 minutes. For our use case, we want to do conditional sampling, but we want to use ranges for the conditional samples. This is (b) from what you mentioned. An example is I want the column constraints X > 10, and Y < 5, and I want to sample rows with these constraints. I want to be able to arbitrarily change these constraints on the fly without retraining the model. It's not a current functionality to have these conditional sampling methods that use resampling strategies as far as I am aware.

**Comment by npatki** [comment]
Hi @Oufattole, circling back to this though with some updates:

The preferred solution is to use [conditional sampling](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html#conditional-sampling). There is now a new API. You can input a dataframe containing all the values you want (X>10 and Y<5) and it will fill out the rest. If you'd like a convenience method for this, feel free to file a new feature request!

We are defining **constraints** as rules that are true of every single row in your data. Currently, it is out-of-scope to make the model learn different values than what's observed in the real data. If we ever do decide to bring this back into scope, we can update the community.

I'll close out the issue since it's a bit stale. Feel free to re-open if you'd like to discuss more or file a new feature request as needed.
