### ISSUE TITLE
Single table - Constraints including multiple columns

### ISSUE THREAD

**Issue by mlee1382** [sdv-dev/SDV#430]
### Environment details

* SDV version: 0.8.0
* Python version: 3.6.8
* Operating System: linux

### Problem description

(Sorry in advance that I could not share any data since it is confidential).

I am trying to generate a synthetic data set for a single table with using lots of constraints.
Introducing simple constraints (e.g. age should always > 0) works well. However, the data set contains a lot of information about customers and some of them have logical relation. For example, for those clients younger than 18, there should not be any credit amount. So ignoring such constraints leads to many inconsistent records. Now when I introduce such constraints with **CustomConstraint** along with **is_valid** arg. I get **Could not get enough valid rows within x trials**. No matter what values I used for the sample args (max_rows_multiplier, max_retries and float_rtol), I always ran into the same issue. So I used **transform** approach trying to mimic the code in https://github.com/sdv-dev/SDV/issues/303. But could not implement successfully.

### What I already tried

```
from sdv.constraints import Constraint

class MyCons(Constraint):

    def __init__(self, columns):
        self._columns = columns

    def transform(self, table_data):
        table_data = table_data.copy()
        table_data[self._columns] = table_data[self._columns].astype(float)
        
        return table_data

    def reverse_transform(self, table_data):

        column_data1, column_data2 = self._columns
        
        table_data[self._columns] = table_data[((table_data[column_data1] <= 20) & (table_data[column_data2] == 0.0)) | 
        ((table_data[column_data1] >= 80) & (table_data[column_data2] == 0)) | 
        (((table_data[column_data1] < 80) & (table_data[column_data1] > 20)) & (table_data[column_data2] >= 0))][[column_data1, column_data2]]
        return table_data

constraint = MyCons(['AGE','CREDIT_AM'])
```
As seen I want the credit amounts to be equal to 0 for those clients younger (older) than 20 (80) and for the rest any amount larger than or equal to 0 is OK.

This constraint returns NaNs for AGE & CREDIT_AM for the first 2 conditions (0 for those younger (older) than 20 (80)) while there is synth data for the rest. How should I introduce such constraints?

Many thanks in advance!

**Comment by npatki** [comment]
Hi! I'm not sure if I'll be able to answer your question completely without more details about your use case. I'm going to assume the following:
- Because you have so many constraints, a simple `reject sampling` approach is failing because it's become very rare for the synthesized rows to pass all the cases
- Instead of `reject sampling`, a more efficient approach is to use `reverse transformations` to "fix" the data when it is incorrect
- You've tested your `reverse_tranform` method to ensure that it's modifying invalid rows to output valid rows for your dataset  -- ie it's properly setting the data to NaN for users <20 or >80

Given this, I'd try:

1. Subclassing [CustomConstraint](https://sdv.dev/SDV/api_reference/constraints/api/sdv.constraints.CustomConstraint.html) instead of `Constraint`. All the current constraints subclass this way. As an example, reference the code for [UniqueCombinations](https://sdv.dev/SDV/_modules/sdv/constraints/tabular.html#UniqueCombinations)
2. Follow the examples in the [user guides](https://sdv.dev/SDV/user_guides/single_table/constraints.html#defining-constraints) using your `MyCons` constraint instead of the ones shown (`GreaterThan` and `UniqueCombinations`)

Hope that works!

**Comment by npatki** [comment]
I'm closing this issue out since we've discussed solutions and it's been a while since any updates. Please feel free to reopen if you have any other feedback!
