### ISSUE TITLE
Constraints don't work in HMA1

### ISSUE THREAD

**Issue by avico78** [sdv-dev/SDV#431]
is there an a way using constraints with HMA1 ?

**Comment by npatki** [comment]
In theory, I believe there's a way to do this using a a workaround described in #296 but official support for this isn't available yet.

**Comment by avico78** [comment]
@npatki thanks , 
is there a plan add support constraints with hma1?
for the  workaround .
following @csala 
" dump the metadata as a JSON or dict and define the constraints there..."
Is there a chance u have some an example how it can be done? or explain what exact steps needed ?
it would be really helpful we have such an example of HMA1 documentation.

**Comment by npatki** [comment]
We've been getting a lot of good usage & feedback about constraints. I don't know which exact release this will be a part of, but fixing this is in the TODO list!

> Is there a chance u have some an example how it can be done? or explain what exact steps needed ?

I added a comment to #296 with some more detailed steps so it's documented all in one place. I'm closing this issue out in favor of this older issue so that our conversation can be streamlined.
