### ISSUE TITLE
Setting column values to null or zero based on other column

### ISSUE THREAD

**Issue by onacrame** [sdv-dev/SDV#436]
I would like certain numeric fields to either be null or 0 based on the value of another column.  For example if column A =1, then certain numeric fields are always nonnull.  If column A = 2, then certain numeric fields MUST be null (or in other cases 0).

How would I implement this?  Thanks

**Comment by npatki** [comment]
This can be accomplished using the `CustomFormula` constraint, described in [this user guide](https://sdv.dev/SDV/user_guides/single_table/constraints.html#customformula-constraint).

The user guide shows how to make a column `years_in_the_company` equal to a computation `age  - age_when_joined`. In your case, you can just replace the computation with your own logic.

**Comment by onacrame** [comment]
> This can be accomplished using the `CustomFormula` constraint, described in [this user guide](https://sdv.dev/SDV/user_guides/single_table/constraints.html#customformula-constraint).
> 
> The user guide shows how to make a column `years_in_the_company` equal to a computation `age - age_when_joined`. In your case, you can just replace the computation with your own logic.

Understood, but let's say I did the following (and maybe you have a more elegant way of doing this).  Here I want Column A to be np.nan if Column B is np.nan but otherwise I just want whatever the model output is.  So I do the following:

```
def col_A_fix(data):
     return np.where(data['B']==np.nan, np.nan, data['A']

Col_A_Constraint = ColumnFormula('A', col_A_fix, strategy='transform')

constraints = [Col_A_Constraint]

model.fit(constraints = constraints)

model.sample(100)
```

The above would give me a KeyError  on the sampling step as Column A  is not a column that exists yet in the sampled dataframe.  Column A cannot actually default to an output of the neural network in this case.  The only way this works is if the value of Column A was completely dependent on the value of other columns but we can't really say "give me the GAN output, unless Column B is np.nan, in which case give me np.nan". In training we don't have this issue as Column A we know exists in the dataframe as we supplied it.

**Comment by onacrame** [comment]
> > This can be accomplished using the `CustomFormula` constraint, described in [this user guide](https://sdv.dev/SDV/user_guides/single_table/constraints.html#customformula-constraint).
> > The user guide shows how to make a column `years_in_the_company` equal to a computation `age - age_when_joined`. In your case, you can just replace the computation with your own logic.
> 
> Understood, but let's say I did the following (and maybe you have a more elegant way of doing this). Here I want Column A to be np.nan if Column B is np.nan but otherwise I just want whatever the model output is. So I do the following:
> 
> ```
> def col_A_fix(data):
>      return np.where(data['B']==np.nan, np.nan, data['A']
> 
> Col_A_Constraint = ColumnFormula('A', col_A_fix, strategy='transform')
> 
> constraints = [Col_A_Constraint]
> 
> model.fit(constraints = constraints)
> 
> model.sample(100)
> ```
> 
> The above would give me a KeyError on the sampling step as Column A is not a column that exists yet in the sampled dataframe. Column A cannot actually default to an output of the neural network in this case. The only way this works is if the value of Column A was completely dependent on the value of other columns but we can't really say "give me the GAN output, unless Column B is np.nan, in which case give me np.nan". In training we don't have this issue as Column A we know exists in the dataframe as we supplied it.

In the example I just mentioned, if I choose reject_sampling, you don't run into the same issue, BUT, what does happen is my sample contains no rows where data['B']==np.nan, which is the opposite of what should happen.

**Comment by npatki** [comment]
Ahh thanks for the detailed explanation. Confirming that the `transform` strategy with `ColumnFormula` won't work for this use case. It's meant when one column is completely dependent on the other columns. 

I can't get `reject_sampling` to work with `ColumnFormula` either. I can spin up another bug to look into that.

I think your issue can be resolved using `CustomConstraint` instead of `ColumnFormula`. The right abstraction to "fix" the data is to use a `reverse_transform`. In the below example, I'm using the data from the [tabular demo](https://sdv.dev/SDV/user_guides/single_table/constraints.html#handling-constraints). I'm fixing `'department' = np.nan` only if `'age' < 35`. 

```python
table = load_tabular_demo()

def fix_rows(data):
    data.loc[data['age'] < 35, 'department'] = np.nan
    return data

my_cons = CustomConstraint(reverse_transform=fix_rows) 
model = GaussianCopula(constraints=[my_cons])
model.fit(table)
```

**Comment by Aybikee09** [comment]
When creating fake data with TVAE, I want only the values in the real dataset to be used in a column of the fake data. I mean I want to use only certain numerical values in a column of fake data. For example, let it create values like 16,20,22,33,35,38.. (for example, not 17 or 18. Because I do not want the values that are not in the real dataset) What should I do for this? I would really appreciate it if you can help.
