### ISSUE TITLE
Unclear when to use reject_sampling with ColumnForumla

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#444]
I'm curious when it's at all advantageous to use `reject_sampling` with the [ColumnFormula](https://sdv.dev/SDV/api_reference/constraints/api/sdv.constraints.ColumnFormula.html) constraint. Here's what written in the docs:
> During the transformation phase the column is simply dropped. During the reverse transformation, the column is re-generated by applying the whole table to the given function.

If the column dropped (never modeled) & always regenerated, why is `reject_sampling` even an option for a handling strategy? In order to reject sample a row, the column should already exist (be modeled).

For context: see #436, where `ColumnFormula` only makes sense for with a `reject_sampling` handling strategy

**Comment by fealho** [comment]
Hi @npatki, when you use `reject_sampling` instead of `transform` as the `handling_strategy`, the transformation is never applied, so the column is never dropped. Instead, it "reject samples" the samples directly, meaning that it keeps generating new samples until one of the satisfies the constraint, and rejects all the others.

**Comment by npatki** [comment]
Closing this off since my question has been answered.

When you use `reject_sampling` ...

1.  The transformation phase is skipped so that part of the description doesn't apply.
2. The SDV will synthesize entire rows and reject them if they don't match the formula.
