### ISSUE TITLE
Adding entity_columns to other models

### ISSUE THREAD

**Issue by 9harshit** [sdv-dev/SDV#468]
### Problem description

So PAR models allows to define entity_columns through which I can generate value for same entity (user id or stock symbol). Is there a way to do this with Gaussian Coupla. I am trying to generate location based values (Latitude Column and Longitude Column) for a city in month of FEB. 

TABLE : USER ID (int), TIMESTAMP (datetime), LATITUDE (FLOAT), LONGITUDE (FLOAT)

With Gaussian Coupla I get great distribution and good synthetic value. But for each user I get only one value 
Is there a way to generate value for different rows for same user like we do in PAR MODEL

PAR model is not able to get great distribution of latitude and longitude. Even with 1000 epochs.
----
Real Sample data distribution
         latitude.   	longitude	
std	0.057186	0.062587	

----

Synthetic data distribution
         latitude.   	longitude	
std | 0.023490 | 0.028904

-----

**Comment by npatki** [comment]
Hi @9harshit, 

The `PAR` model is recommended for sequential data. By definition, it seems like your data is sequential: It has multiple sequences (one for each user) and within a sequence, there is a dependency between the rows. The `GaussianCopula` is not meant to handle such cases.  Instead of adding entities to tabular models, the preferred approach would be to improve `PAR` model itself. It would be great if you can file a feature request for this.

If you do not care about the sequential nature of the data, you can use the `GaussianCopula` model and make `USER ID` a categorical variable. You'll then receive multiple rows for each user. However, the synthetic data may be out-of-order with respect to the timestamp, and it may not make sense even if you sort it by timestamp.

**Comment by 9harshit** [comment]
Hello @npatki,

Thanks for the suggestions. I will create a feature request for PAR model to for inter row dependencies. Meanwhile if there is a discussion on approaching this issue, I would like to be included in that to help you implement this feature.

Thanks✌🏻

**Comment by npatki** [comment]
@9harshit sounds good.

To be clear, the PAR model is already able to model inter-row dependencies, so no feature request is needed for that.

The feature request will be if you want to _improve_ what the PAR model does. For example, you mention that that the distribution is not great. What kind of criteria would you use to evaluate a good distribution? That would be the feature request.

**Comment by npatki** [comment]
Hello, this issue has been inactive for over a week now. I'll close it off since we've answered your initial question. Feel free to file a feature request for improving the PAR model synthetic data quality. 

Alternatively, you can reply here if there is more to discuss and I will re-open the issue.

**Comment by 9harshit** [comment]
> @9harshit sounds good.
> 
> To be clear, the PAR model is already able to model inter-row dependencies, so no feature request is needed for that.
> 
> The feature request will be if you want to _improve_ what the PAR model does. For example, you mention that that the distribution is not great. What kind of criteria would you use to evaluate a good distribution? That would be the feature request.


Hi @npatki, first basic evaluation of data would be done using statistical testing while more micro based assessment is done by analyzing user based movement (GPS data movement should be real such traveling 1 km location difference in 30 min valid data but invalid if time elapsed is 30 s ), Time based movement patter, borough based movement and such. I can provide you with more detail of my assessment if needed.

Thanks

**Comment by npatki** [comment]
Thanks @9harshit, if you want to file a feature request for this, that would be great. 

> group data by specific attribute like time or user id and then training the model on each group instance in batch so model learn unique id based relation and macro relation among data

The PAR model currently works by grouping based on the entity columns, and then learning the time-based relationships per entity while factoring in the unchanging, context columns as attributes. We have an outstanding issue #840 for better documentation of the PAR model, which we should hopefully be publishing soon. That may also give some more ideas for this.

**Comment by 9harshit** [comment]
Sure thanks @npatki, I will open up a new Feature Request.
