### ISSUE TITLE
Using constraints in creation of Lat/Long info

### ISSUE THREAD

**Issue by 9harshit** [sdv-dev/SDV#469]
### Problem description

I am trying to generate longitude and latitude info for users.

Is there a way to set constraints on creating lat/lon based on correct area they belong to

user_id | ts | latitude | longitude | WARD_NAME

8080145145683855329 | 2021-02-06 23:42 | 13.006402 | 77.503040 | Hegganahalli
2744968374562492186 | 2021-02-19 02:37 | 12.947452 | 77.540276 | Gali Anjenaya Temple ward
4018900414965388456 | 2021-02-20 04:29 | 13.016450 | 77.596490 | Jayachamarajendra Naga

I want that lat/lon that is generated belong to correct WARD_NAME (area that is)

### What I already tried 

I tried passing the dataset as is to Gaussian Coupla and PAR but most of the lat/lon doesn't belong to the area it mentions in that row 
I tried UniqueCombinations but it display error stating UniqueCombinations is not iteratable.

**Comment by npatki** [comment]
Hi @9harshit

I realize this issue is quite old, but if you are still reading our GitHub, there are a few updates:

> I tried UniqueCombinations but it display error stating UniqueCombinations is not iteratable.

It's possible you were getting this error due to an incompatibility with numerical columns. This was fixed in #481.

>  I want that lat/lon that is generated belong to correct WARD_NAME (area that is)

This is a great feature request for our RDT library. Check out our new [Contextual Anonymization](https://docs.sdv.dev/rdt/transformers-glossary/premium-add-ons/contextual-anonymization) offering. In particular, we can extract region and country code from [phone number data](https://docs.sdv.dev/rdt/transformers-glossary/premium-add-ons/phone-number-data/anonymizedgeoextractor).

Would such functionality be useful to you for GPS data? If so, I'd recommend filing an issue for our [RDT library](https://github.com/sdv-dev/RDT/issues)

**Comment by 9harshit** [comment]
Hi @npatki, Thanks for suggesting RDT Library, I will take a look at it.

I am trying to generate synthetic data for a particular city and further the synthetic GPS data should follow distribution that bounded and true to different regions of the city and is also time constraint {time series data as to study user movement}.

**Comment by npatki** [comment]
Extracting region/city information is something we can do in the Premium RDT. Take a look  and let me know if it's something you'd be interested in.

**Comment by 9harshit** [comment]
> Extracting region/city information is something we can do in the Premium RDT. Take a look and let me know if it's something you'd be interested in.

I will asses RDT's use case on my data and get back to you. Thanks for your suggestions.
