### ISSUE TITLE
 How to generate finite discrete values?

### ISSUE THREAD

**Issue by lym27** [sdv-dev/SDV#502]
### Problem description

When I use ctgan, the value of a certain column that I need to generate is only taken from the four discrete values of 1, 2, 3 and 4. In fact, when I feed the data into the ctgan model, many zero values are generated. I don't want to have zero values. How can I realize it? Thank you!!

**Comment by npatki** [comment]
Thanks for the feedback! This is happening because the SDV is treating the column as numerical, and the statistics will consider the small probability of a value being less than (or greater than) the range observed.

As a short term fix, the soln described in #445 should work.

For the long term, the team is looking into some solutions to make this easier. We'll update this issue when we have a solution.

**Comment by npatki** [comment]
Hello! I'm closing this issue because the latest SDV release`0.11.0` addresses it for `numerical` data. It enforces that the data is in-bounds by default. 

Note: If the integers represent categories without any specific order, continue to use the the fix described in the previous comment. It treats the data as `categorical`, instead of `numerical`.
