### ISSUE TITLE
Dependency Updates

### ISSUE THREAD

**Issue by nviets** [sdv-dev/SDV#534]
Are there any plans to update to a more recent version of Pandas and Sktime? What were the breaking changes in these packages for the SDV packages?

https://github.com/sdv-dev/SDV/blob/master/setup.py#L18

**Comment by csala** [comment]
There are plans to upgrade at some point, but there is no specific timeline, since it involves multiple libraries and a lot of things need to be validated and certified before making the change.

Just for curiosity, can I ask what is your use case and why using the current pandas and sktime version ranges is a problem?

**Comment by nviets** [comment]
Hi @csala, thanks for the prompt reply! I'd like to use the SDV libraries within a nixpkgs based environment, which has updated to [pandas 1.2.3](https://github.com/NixOS/nixpkgs/blob/release-21.05/pkgs/development/python-modules/pandas/default.nix). SDV is one of the only packages tied to the older pandas, which is holding back the larger udpate. Sktime is similar, but it's easier to limit the version since it's used in fewer package in the same setup.

**Comment by csala** [comment]
Thanks for clarifying @nviets

A few issues have been open that cover this (see #558, [Copulas #266](https://github.com/sdv-dev/Copulas/issues/266) and [SDMetrics #69](https://github.com/sdv-dev/SDMetrics/issues/69)), so I'm closing this issue in favor of the other ones that are more explicit.
