### ISSUE TITLE
`GaussianCoupla` has problems generating missing values (especially with constraints)

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#551]
**Observed**: The `GreaterThan` constraint correctly synthesizes numerical data that follows the constraint. However, no missing values are ever generated, even if the original data has missing values.

* Original data: Has a constraint where `paid_off > loan_started`. However not all loans have been paid off so `NaN` values are also possible.

| loan_started    |  paid_off  |
| ----------- | ----------- |
|  2018-09-10      |  2021-01-08       |
| 2020-04-12   |  NaN        |
| 2016-07-23   |  2020-06-09        |
| 2015-08-04   |  2020-07-31        |
| 2021-08-08   |  NaN  |

* Synthesized data: Will not ever include `NaN` values in the `paid_off` column. 

**Expected**: Synthesized data should include `NaN` values in the `paid_off` column. When the values are not null, then `paid_off > loan_started`, similar to the input data.

**Comment by npatki** [comment]
Update: After some more investigation, I've learned that:

1. This is only happening when I use the `GaussianCopula` model, not any of the other models 
2. `GaussianCopula` is very rarely generating `NaN` values even without the constraint and
3. It's actually working as intended when I use other datasets

It's possible that `GaussianCopula` is just unable properly capture this correlation for this dataset, but I don't know why. I observed something similar with test data:

```python
import numpy as np
import pandas as pd
from sdv.tabular import GaussianCopula, CTGAN

d = {'col1': [2, 4, 6, 2, 4, 6, 8, 9, 7, 1], 'col2': [3, 5, 8, np.nan, np.nan, 7, 9, 10, np.nan, 3]}
df = pd.DataFrame(data=d)

cons = GreaterThan(
    low='col1',
    high='col2'
)

# GaussianCoupla with constraints
model = GaussianCopula(constraints=[cons])
model.fit(df)
synth = model.sample(1000) # no nulls generated

# try without constraints 
model2 = GaussianCopula()
model2.fit(df)
synth2 = model2.sample(1000) # no nulls generated

# try with a different model
model3 = CTGAN(constraints=[cons])
model3.fit(df)
synth3 = model3.sample(1000) # nulls finally generated!

```

**Comment by csala** [comment]
Very interesting. What is strange is that `GaussianCopula` seems to do really good in capturing `NaN` values. For example, [the demo dataset shown in the GaussianCopula User Guide](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html#generate-synthetic-data-from-the-model) seems to be properly modeled, not only because it generates the `NaN` values, but also because it properly learns how multiple columns need to be `NaN` at the same time.

I am curious about a couple of things:
- What `distribution` does the `GaussianCopula` assign to the Null indicator column? You should be able to get it by executing `model.get_distributions()[f'{column_name}#1']`
- Does `CopulaGAN` have the same problem? Since it also uses the `GaussianCopulaTransformer`, the problem could be the univariate distribution selection.

**Comment by npatki** [comment]
With the current test dataset, `CopulaGAN` does successfully generate `nan` values but with low probability. Out of 1000 synthesized rows, only 10 rows have missing values.

All models are showing: `StudentTUnivariate`

For `GaussianCopula`, the reported parameters for this column:

```python
{ 'univariates__col2#1__df': 0.5070785583345971,
 'univariates__col2#1__loc': 3.9825168544702007e-16,
 'univariates__col2#1__scale': 1.1816398885516025e-15 }
```

Could it be due, instead, to the computed correlations? Making it unlikely (but not _impossible_) for `nan` values?

**Comment by npatki** [comment]
This issue is now stale, as our work on SDV 1.0 and RDT 1.0 has fixed the underlying bugs.
