### ISSUE TITLE
`GreaterThan` constraint crashing with `NaN` values

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDV#592]
As reported in issue #590 and #589, the `GreaterThan` seems to be failing in the presence of NaN values. The cause seems to be the following line:

https://github.com/sdv-dev/SDV/blob/061d69b93f8d4ca8b974da158bc76b67c44b00eb/sdv/metadata/table.py#L593

Basically, since `NaN` values are not comparable, this line is returning `false` for the comparison between `NaN`'s, which causes the code to crash.

We should work on a fix, seeing as this error happens with our demo dataset (student_placements).

**Comment by npatki** [comment]
FYI same thing is happening with `ColumnFormula` -- raised in #593

Under the hood, the `is_valid` methods for each constraint check for validity.  In this case, `GreaterThan` seems to be using `np.greater` or `np.greater_equal`. These will output `False` whenever they encounter `NaN` values. 

I think we should just ignore `NaN` values since they clearly don't apply to a `GreaterThan` constraint.

**Comment by katxiao** [comment]
@npatki I have a follow-up to the proposal of ignoring `NaN` values. 

If we have a GreaterThan constraint on two columns `a` and `b` (`a > b`), I think it makes sense to ignore a row where both `a` and `b` are `NaN`, and return `True` for that row. However, if `a` is non-null and `b` is null, that row seems invalid and I think we should return `False` in that case. 

What do you think?

**Comment by npatki** [comment]
@katxiao To me, the most straightforward interpretation of `GreaterThan` is: `a > b` if and only if `a` is present and `b` is present. We should return `True` whenever the `>` operator doesn't really apply.
1. Both values are missing or
2. One of the values is missing

Otherwise, I'm not sure how the user would handle the situation where certain values may be missing randomly.

**Comment by npatki** [comment]
One motivating example to the above: In the [Loan dataset ](https://www.kaggle.com/zhijinzhai/loandata)on Kaggle, there is a constraint that the loans `paid_off_time > effective_date`. However, not all loans are paid off. So if `paid_off_time` is missing, then I don't expect the `>` constraint to apply (return `True`)
