### ISSUE TITLE
In HMA1, can we use a primary key which is categorical?

### ISSUE THREAD

**Issue by poornima-sivanand** [sdv-dev/SDV#640]
### Environment details

If you are already running SDV, please indicate the following details about the environment in
which you are running it:

* SDV version:0.12.1
* Python version:3.8.12
* Operating System: MacOS Big Sur 11.6

### Problem description

I am trying to use SDV to synthesize relational data and for learning to use it, I am using synthea covid-19 dataset from https://synthea.mitre.org/downloads. The Patient Ids or the primary keys in the dataset are alphanumeric and an example is "00049ee8-5953-4edd-a277-b9c1b1a7f16b". This seems to be of type id, subtype string. However, when the data is generated, the value for patient ids is generated as a, b , c etc. due to which it throws an error during evaluation.

**Comment by katxiao** [comment]
Hi @poornima-sivanand, thanks for your question. Yes, you can use a primary key that is categorical.

It seems that the sampled data is being generated correctly, but you are running into an error when calling `sdv.evaluate`. 
The error during evaluation is due to a bug in `sdmetrics` -- `evaluate` should accept id columns that differ in values from the real data. There was a bug where `evaluate` was wrongly erroring out on mismatched ids. The [fix](https://github.com/sdv-dev/SDMetrics/pull/105) is already in our codebase, and will be going out in the next SDV release.

An additional note -- if you want the patient IDs to fit a certain format, you can specify an optional regex field, as shown [here](https://sdv.dev/SDV/developer_guides/sdv/metadata.html?highlight=pii#primary-key-fields).

**Comment by katxiao** [comment]
Hi @poornima-sivanand, please try the evaluation again with the newest SDV release (`v0.13.1`).

**Comment by npatki** [comment]
Hi everyone, I'm closing this issue out since the question has been discussed and it's been inactive for a while. Please feel free to re-open if you have further comments or feedback!
