### ISSUE TITLE
Metadata does not parse `categorical` column types

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDV#665]
### Environment Details

* SDV version: 0.13.0

### Error Description

I have a few columns which are represented as integers but actually describe categories.

| phone_number      |  http_response |
| ----------- | ----------- |
| 4085559111      |  404       |
| 6175551234   | 202        |

I have specified these types as `categorical` in my Metadata and I'm using the Metadata class to load in the csv. However, it does not parse these types as objects; they remain ints.

### Solution

The [`parse_dtypes`](https://github.com/sdv-dev/SDV/blob/3af5fe73a181714fa1a8691b2df2e17627fb5e49/sdv/metadata/dataset.py#L30) method is only casting `datetime` and `integer` columns. It is not not checking for columns that need to be converted to strings (aka objects):
* `field_type = 'categorical'`
* `field_type == 'id' and field.get('subtype') == 'string'`

Both should be recast as `string`.

(Additionally, we should also audit what is happening with `boolean` type. I don't see any checks for it here either.)

**Comment by xamm** [comment]
For `boolean` types this problem seems to exist as well.

If this is fixed for boolean types, it should be discussed what the behavior should be, since simple parsing of columns to `boolean` would result in any columns with 2 values being parsed, while columns with more than 3 unique values would have an error.
If this is the expected behavior, simple parsing would be fine.

e.g.
- [x]  `[True, False] -> parsing works` 
- [x]  `[1, 0] -> parsing works`
- [x]  `[-1, 0] -> parsing works`
- [x] `[0, 1, 2] -> parsing fails`

**Comment by npatki** [comment]
Closing this issue, as this is working as intended.

We are considering the computer representation of a column (eg. `object`, `int`, `str`) as a completely separate concept than the SDV data types. A single data type (such as `"categorical"`) could be represented in multiple ways.

More details & examples [here](https://docs.sdv.dev/rdt/usage/basic-concepts/sdtypes).
