### ISSUE TITLE
How to handle Multiple Special Values? 

### ISSUE THREAD

**Issue by mghorpa** [sdv-dev/SDV#679]
### Environment details
* SDV version: 0.11.0
* Python version: 3
* Operating System: Windows

### Problem description

I have multiple special values in the data. So a column might have -5 and -1 as special values. When modeling with Gaussian Copula on this data, as the column originally is numeric the model treats the special values as numeric and it will change the distribution for that column. Hence, the synthetic data generated contains continuous values from -5 to -1 instead of considering these as special values. Is there a work around for this? Also, is there a way to use multiple special values?

For Example-
Input data: column ranges from 0 to 700 and has 2 special values -1 (2000 observations) and -5 (10 observations) 
Output synthetic data: column ranges from -5 to 700 and instead of just 2 special values, there are 5 negative values -1,-2,-3,-4 and -5 values with ~ 300 observation's each

### What I already tried

I have tried replacing both the special values with one special value. Tried it using below 2 ways- 
1. Replaced with -999: This changed the output distribution completely. The model considered it as this as one of the continues value and outputs multiple negative values ranging from -999 to 0 
2. Replaced with -1: As the column value starts from 0, considered replacing all the special values with -1. It sill considers it as a continuous value however it is the closest solution I could think of. This is still an issue because it will change the distribution of input column and intern will affect gaussian copula model performance as it is learning from this distribution

**Comment by npatki** [comment]
Hi @mghorpa, by default the SDV will model a numerical on a continuous scale. You may have some luck changing the special values, that approach will ultimately just affect the learned distribution.

It seems you actually have a column with a mix  numerical and categorical data. This is not explicitly supported, but here are some workarounds:

1. Replace all special values with `np.nan`. The SDV is designed to model & re-create missing values. Con: you will lose the ability to distinguish special values (-1 vs. -5).
2. Model the column as categorical instead of numerical (using [metadata](https://sdv.dev/SDV/developer_guides/sdv/metadata.html) or alternatively by casting the column as a string). Con: the `fit` process may take longer and values that are continuous will not be modeled.
3. Modify your dataset logic to isolate numerical vs. categorical data. Con: Some logic required for pre-processing and may require more trial-and-error.

Let me know if that works.

**Comment by npatki** [comment]
Hi, I'm closing off this issue since answer your question. Please re-open if you have any follow-ups!
