### ISSUE TITLE
scikit-learn version conflict with pycaret

### ISSUE THREAD

**Issue by dyuliu** [sdv-dev/SDV#685]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDV version: v0.13.1 and v0.12.1
* Python version: 3.6
* Operating System: linux

### Error Description

I am using `pycaret` to do benchmarking for regression tasks on single tabular data. We are testing whether we can enhance ML performance by adding synthetic data to our training data.

However, `SDV v0.13.1` is using `CTGAN v0.5.0` which requires **'scikit-learn>=0.24,<2'**.  `pycaret` requires exactly **scikit-learn==0.23.2** and this does not meet CTGAN's minimum version requirement. 

Though `SDV v0.12.1` which uses `CTGAN v0.4.3` is compatible with **scikit-learn==0.23.2**, it has a bug when I try to use ctgan or copulaGAN. 

**Here is a brief description about this bug and can be helpful to reproduce it:**
The training data contain 6 columns (3 categorical + 3 numeric). The numbers of unique values of the three categorical variables are 2, 51, and 17 which are pretty small I believe. My training data is of shape (40000, 6), and there is no constraints specified for testing purpose.  The bug is at a certain point a dataframe of shape (40000, 40000) will be created and it eats a lot of memory and soon we get an out of memory error. 

This bug is gone in `SDV v0.13.1` which is good. However, I cannot use `SDV v0.13.1` in my workflow as I explained in the beginning.

### Suggestions

The best solution to me is to loose `scikit-learn` version in `CTGAN v0.5.0` to **>=0.23**

The sub-optimal solution would be to fix the ctgan bug in `SDV v0.12.1`

**Comment by npatki** [comment]
Hi @dyuliu and @RomainPalazzo, thanks for the detailed description.

Unfortunately, we're unable to bring the min version of `scikit-learn` back down to 0.23. The version was bumped because we want to support Python 3.9 -- and not all platforms can run `scikit-learn v0.23` along with Python 3.9.

**Possible Workaround:** It seems to be like you're using `pycaret` as a second step after creating synthetic data, right? Though it's not the cleanest, you can then split up your workflow in the following way:

1. Create an environment with `sdv v0.13.1` to do the modeling and generate the synthetic data. Save the synthetic data to a csv file.
2. Create a separate environment with `pycaret` and `scikit-learn v0.23.2`. Load the synthetic data from the csv and use it there. 

BTW do file a bug if you're continuing to notice sporadic memory errors in modeling. I've yet to replicate this.

**Comment by npatki** [comment]
Hello, this issue has been inactive for a while. I'll close it off since it seems like we have a workaround, even though we unfortunately can't fix the underlying version conflict.

Feel free to reply if there's more to discuss and I'll reopen the issue!
