### ISSUE TITLE
HMA1 fit function runs indefinitely and crashes after 30min of execution on a tiny dataset

### ISSUE THREAD

**Issue by moben1** [sdv-dev/SDV#738]
### Environment Details

* SDV version:  0.13.1
* Python version: 3.8
* Operating System: Ubuntu 20.04.4 LTS

### Error Description

I was trying to train the model HMA1 for 3 tables, the training ran indefinitely and stopped by a SIGKILL. I tried to reduce the tables sizes down to 20 rows and I was facing the same issue. When I try for one table it runs within a couple of seconds but as soon as I add another table it takes too long and crashes at the end.
### Steps to reproduce
Client_Details table contained 36 columns and 10 rows
Trip_summary table contained 150 columns and 25 rows

```
def test_sample_data(table_dict: Dict[str, pd.DataFrame]):
        metadata = Metadata()
        metadata.add_table(
            name='CLIENT_DETAILS',
            data=table_dict["CLIENT_DETAILS"],
            primary_key='CLIENT_ID',
        )
        # todo check the start date for the trip summary
        metadata.add_table(
            name='TRIP_SUMMARY',
            data=table_dict['TRIP_SUMMARY'],
            primary_key='TRIP_ID',
            parent='CLIENT_DETAILS',
            foreign_key='CLIENT_ID',
        )

        # metadata.add_table(
        #     name='RIP_COMPLEMENT_INFO',
        #     data=table_dict['TRIP_COMPLEMENT_INFO'],
        #     primary_key='TRIP_COMPLEMENT_INFO_ID',
        #     parent='TRIP_SUMMARY',
        #     foreign_key='TRIP_ID',
        # )

        model = HMA1(metadata)
        model.fit(table_dict)
        new_data = model.sample(num_rows=20)
        display(table_dict['CLIENT_DETAILS'])
        display(new_data["CLIENT_DETAILS"])
        display(table_dict['TRIP_SUMMARY'])
        display(new_data["TRIP_SUMMARY"])e.
```
And I get this message after maybe 30min of the code running 
```
/home/momoben/.local/lib/python3.8/site-packages/sdv/relational/hma.py:255: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  table.reset_index(inplace=True)

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

**Comment by katxiao** [comment]
Hi @moben1 - Based on the stacktrace you provided, it seems like the process is running out of memory and is being terminated as a result. I'm curious how much memory you have available in your environment?

If your dataset has categorical columns, one suggestion to try is to use one of the other categorical transformers (`categorical`, `categorical_fuzzy` or `label_encoding`), since the default categorical transformer (OneHotEncoding) can  be less memory efficient.

```python
model = HMA1(
    metadata,
    model_kwargs={
        'categorical_transformer': 'categorical_fuzzy',
    },
)
```

**Comment by Erenhub** [comment]
@katxiao, the trip dataset contains generally origin-destinations as categoric variables, which creates a big load on memory, for example if you have 4000 origin destinations, it creates 4000^2 columns with one hot encoding. I tried switch from one hot encoding to categorical_fuzzy in my code, but still it was not sufficient to solve this complexity.

**Comment by npatki** [comment]
Katharine's suggestions may help improve the modeling time. We are discussing the performance implications in a few other places, so I'll close off this issue in favor of these other issues:

- Modeling time performance: #830 
- Memory usage: #805 

Please feel free to continue the conversation on these issues.

**Comment by Erenhub** [comment]
Hi @npatki , thanks for your reply and I apologize for replying late. My real problem in this project is, the GPS coordinates given categorical, we have 1000+ categoric district for Brisbane City. I used centroid locations to reduce complexity a bit. But my real problem is, since we are giving two different 1000+ columns as origins-destinations, synthetic data have slightly different distribution, where it underestimates short trips and overestimate long trips. I am already using fixedcombinations.

I am lately thinking to create some trajectories to get rid of origin destination problem, also thinking to use different transformer for geolocation data. I read the documents and I think the current algorithm and transformers are covering different kind of datasets, since there are transformers for discrete and continuous data types. provided by your side. Mathematically, would that makes sense to use different type of transformer rather than bgm? Also, would you be interested working collaboratively on this research topic?

Kind Regards.
