### ISSUE TITLE
Score of privacy evaluation metric NumericalLR

### ISSUE THREAD

**Issue by san1ker** [sdv-dev/SDV#772]
* SDV version: master
* Python version: 3.8.10
* Operating System: macOS

https://sdv.dev/SDV/user_guides/evaluation/single_table_metrics.html mentions about score like 

     "The output of this metric is between 0 and 1, where the closer the value is to 0, the less private it is."

but "less private" is a little bit ambiguous to me.

So my question is 

- 0 is good score?? or 1 is good score??
- Also I want to know the range of good score

thanks:)

**Comment by npatki** [comment]
Hi @san1ker, great question.

The privacy metrics work by fitting an adversarial attack model -- that is, we pretend to be an attacker with access to the synthetic data and the key fields; we attempt to guess the _real_ sensitive_ fields with this info. A score of 0 means that an attacker can correctly guess the values in _all_ of the rows. Hence, it is "less private".

Given this, a "good score" should be high. Exactly how high is really dependent on your dataset. You may have one where it's generally very easy to guess due to strong correlations. Your assessment should include the risk of an attacker having access to the real key fields.

**Comment by san1ker** [comment]
Thanks for the answer. Now it's clear :)
