### ISSUE TITLE
Installation Error for Python version > 3.8. 

### ISSUE THREAD

**Issue by Uzzije** [sdv-dev/SDV#785]
### Environment Details

Please indicate the following details about the environment in which you found the bug:
Attempting to install `pip install sdv`

* SDV version: latest release
* Python version: > 3.8 
* Operating System: Mac M1

### Error Description
<img width="903" alt="Screen Shot 2022-05-05 at 6 27 24 PM" src="https://user-images.githubusercontent.com/5669956/167042859-a7b322fc-beea-4daf-9f73-5aa627e463f8.png">

### Steps to reproduce
```
pip install sdv
```

**Comment by npatki** [comment]
Hi @Uzzije, I'm unable to replicate this with the latest version of the software. I am on a Mac M1 chip with Python `3.9.13` and successfully installed SDV `0.15.0`. 

Some things to confirm:
- The latest SDV version was released after this issue. Try installing this version explicitly `pip install sdv==0.15.0`
- Are you using a virtual environment to ensure that other installed libraries are not conflicting with this one?
- Can you successfully install other data science libraries such as `numpy`, `scipy` and `sklearn`?

BTW on the M1 chip specifically, I have had the most success installing using [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/download.html#anaconda-or-miniconda) rather than pip. If you want to use pip, others have reported success with [running the terminal in Rosetta mode](https://apple.stackexchange.com/questions/409746/run-everything-in-rosetta-2-on-silicon-mac).

**Comment by npatki** [comment]
Hello, this issue has been inactive for some time now. I'm closing it off since we've discussed a few options to try. Feel free to reply if you are still have problems installing and I can reopen the issue.
